<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
?>
<div class="twelvecol last">
	<div class="content">
		<h1>
			<?= $objCore->getHelperTranslator()->_("Location") ?>
		</h1>
		<div style="float: right; text-align: right;">
			<strong>
				Schmolck GmbH &amp; Co. KG
			</strong>
			<br>
			Am Elzdamm 2
			<br>
			79312 Emmendingen
		</div>		
		<p>			
		<form method="get" action="https://maps.google.de/maps" target="_blank">
			<input type="hidden" name="daddr" value="Am Elzdamm 2, 79312 Emmendingen">
			<input type="text" name="saddr" style="width: 45%;" title="<?= $objCore->getHelperTranslator()->_("Enter your address here") ?>">
			<input type="submit" value="<?= $objCore->getHelperTranslator()->_("Search") ?>">
		</form>
		</p>
		<p>
			<iframe width="100%" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps/ms?msa=0&amp;msid=210111196947745233323.00046c60ab25feb767013&amp;hl=de&amp;ie=UTF8&amp;ll=47.963208,7.736156&amp;spn=0.296355,0.23316&amp;t=m&amp;iwloc=00046c60c37a60af797b4&amp;output=embed"></iframe>
			<br>
			<small>
				<a href="https://maps.google.com/maps/ms?ie=UTF8&amp;msa=0&amp;msid=210111196947745233323.00046c60ab25feb767013&amp;t=h&amp;ll=47.963261,7.735748&amp;spn=0.441392,0.878906&amp;z=10&amp;source=embed" target="_blank">
					<?= $objCore->getHelperTranslator()->_("Schmolck Group") ?>
				</a>
				- 
				<?= $objCore->getHelperTranslator()->_("open in a larger map") ?>
			</small>
		</p>
	</div>
</div>