<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$nCounter = 0;

/*
 * OUTPUT
 */
// - detail view
if ($objCore->strParameterId != '') {
	?>
	<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?> loading">
		<script>
			Schmolck_Framework_Helper_Api({
				id: '<?= $objCore->strId ?>',
				url: 'api/cars/detail',
				data: '<?= http_build_query(array_merge($_GET, $_POST)) ?>'
			});
		</script>
	</div>
	<?php
	return;
}
// - list view
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<div class="list">
		<? foreach ($objCore->arrCars as $arrCar) : ?>		
			<? ($nCounter % 2 == 1) ? $strOdd = 'odd' : $strOdd = ''; ?> 
			<div class="item <?= $strOdd ?>" data-link="<?= $objCore->strParameterUrl ?>/id/<?= $arrCar['KNR'] ?>">
				<div class="title">
					<?= $arrCar['name'] ?>
				</div>
				<div class="data">
					<div class="image">
						<img src="<?= $arrCar['image'] ?>">
					</div>
					<div class="infos1">
						<?= $arrCar['KAT'] ?> <br>
						<?= $arrCar['KNR'] ?> <br>						
					</div>
					<div class="infos2">
						EZ <?= $arrCar['EZ'] ?> <br>
						<?= $arrCar['KM'] ?> km <br>
					</div>
					<div class="infos3">
						<?= $arrCar['KW'] ?> kW (<?= $arrCar['PS'] ?> PS) <br>
						<?= $arrCar['color'] ?> <br>
					</div>
					<div class="price">
						<?= $arrCar['RP'] ?> EUR <br>
					</div>
					<div class="clearer">
						&nbsp;
					</div>
				</div>
			</div>
			<? $nCounter++ ?>
		<? endforeach; ?>
	</div>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>