<!DOCTYPE html>
<html>
	<head>
		<!--
		Memory Peak Usage: <?= Schmolck_Tool_File::convertBytes(memory_get_peak_usage()) ?>
		-->		
		<base href="<?= $objCore->getHelperApplication()->getBaseUrl() ?>">
		<meta charset="utf-8"/>
		<title>
			Schmolck
		</title>
		<link rel="icon" type="image/png" href="images/www.schmolck.de/favicons/favicon.png">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" type="text/css" href="apps/style/<?= $objCore->getLayoutStyleFile() ?>" media="all"/>

		<!--[if lt IE 9]>
		<link rel="stylesheet" type="text/css" href="<?= $objCore->getHelperApplication()->getTemplatePath() ?>/styles.ie.css" media="all"> 
		<![endif]-->
		
		<!--[if lt IE 9]>
		<link rel="stylesheet" type="text/css" href="<?= $objCore->getHelperApplication()->getTemplatePath() ?>/styles.ie8andlower.css" media="all">   
		<![endif]-->
		
		<!--[if lt IE 8]>
		<link rel="stylesheet" type="text/css" href="<?= $objCore->getHelperApplication()->getTemplatePath() ?>/styles.ie7andlower.css" media="all">     
		<![endif]-->		
		
		<script type="text/javascript" src="apps/script/<?= $objCore->getLayoutScriptFile() ?>"></script>		
	</head>
	<body>
		
		<header>
			<div class="container">
				<?= $objCore->getHelperApi()->getElement("{$objCore->strId}_image", 'portal/index/slider', array(
					 'path' => 'images/www.schmolck.de/plugins/image/slider'
				));
				?>
			</div>
		</header>

		<secion id="main">
			<div class="container">
				<?= $this->renderViewHtml() ?>
			</div>			
		</section>

		<? if (PIWIK_TRACKING_ID != '') : ?>
			<?= Schmolck_Tool_Piwik::getTrackingCode(PIWIK_TRACKING_ID); ?>
		<? endif; ?>
		
	</body>	
</html>