<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <div class="contact">
        <div class="row">
            <div class="col-md-6">
                <h1>
                    <?= $objCore->getHelperTranslator()->_("Details") ?>
                </h1>
            </div>            
        </div>
    </div>
</div>