<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * PREPARATION 
 */
if ($objCore->bAutoSubject) {
    $strSubjectDisabled = 'disabled';
}
// - CSS classes for error display
$arrElement = array(
    'name' => array(
        'label' => $objCore->getHelperTranslator()->_("Name") . '*',
        'error' => $objCore->strErrorName
    ),
    'email' => array(
        'label' => $objCore->getHelperTranslator()->_("E-Mail") . '*',
        'error' => $objCore->strErrorEmail
    ),
    'subject' => array(
        'label' => $objCore->getHelperTranslator()->_("Subject") . '*',
        'error' => $objCore->strErrorSubject
    ),
    'message' => array(
        'label' => $objCore->getHelperTranslator()->_("Message") . '*',
        'error' => $objCore->strErrorMessage
    )
);
foreach ($arrElement as $element => $value) {
    if ($value['error'] != '') {
        $arrElement[$element]['class'] = 'has-warning';
        $arrElement[$element]['label'] = $value['error'];
    } else {
        $arrElement[$element]['label'] = $value['label'];
    }
}

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <form method="post">
        <? if ($objCore->strMessageMail != '') { ?>
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?= $objCore->strMessageMail ?>
        </div>
        <? } else { ?>
        <input type="hidden" name="send" value="1">

        <div class="form-group <?= $arrElement['name']['class'] ?>">
            <label for="name" class="control-label">
                <?= $arrElement['name']['label'] ?>
            </label>
            <input id="<?= $objCore->strId ?>_name" class="form-control" type="text" name="name" value="<?= $objCore->strName ?>">	
        </div>

        <div class="form-group <?= $arrElement['email']['class'] ?>">
            <label for="email" class="control-label">
                <?= $arrElement['email']['label'] ?>
            </label>
            <input type="text" name="email" class="form-control" value="<?= $objCore->strEmail ?>">
        </div>

        <div class="form-group <?= $arrElement['subject']['class'] ?>">
            <label for="subject" class="control-label">
                <?= $arrElement['subject']['label'] ?>
            </label>
            <input type="text" name="subject" class="form-control" value="<?= $objCore->strSubject ?>" <?= $strSubjectDisabled ?>>
        </div>

        <div class="form-group <?= $arrElement['message']['class'] ?>">
            <label for="message" class="control-label">
                <?= $arrElement['message']['label'] ?>
            </label>
            <textarea name="message" spellcheck="true" class="form-control"><?= $objCore->strMessage ?></textarea>
        </div>

        <div class="form-group">
            <input class="btn btn-default" type="reset" value="<?= $objCore->getHelperTranslator()->_("Reset") ?>">
            <input class="btn btn-primary" type="submit" value="<?= $objCore->getHelperTranslator()->_("Submit") ?>">
        </div>

        <?= $objCore->getHelperScripts()->renderViewScripts() ?>

        <? } ?>
    </form>
</div>