<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
// - style
$strStyleClass = $objCore->getHelperApi()->getStyleClass();
// - button
$strButtonLabel = sprintf($objCore->getHelperTranslator()->_("Display %s hits"), $objCore->nCount);

/*
 * PREPARATION
 */
// - brands
$arrBrands = array(
	'all' => $objCore->getHelperTranslator()->_("All"),
	'mercedes-benz' => $objCore->getHelperTranslator()->_("Mercedes-Benz"),
	'smart' => $objCore->getHelperTranslator()->_("smart"),
	'others' => $objCore->getHelperTranslator()->_("Others"),
);
// - models
$arrModelsMercedes = array(
	"all" => $objCore->getHelperTranslator()->_("All"),
	"a" => $objCore->getHelperTranslator()->_("A-Class"),
	"b" => $objCore->getHelperTranslator()->_("B-Class"),
	"c" => $objCore->getHelperTranslator()->_("C-Class"),
	"e" => $objCore->getHelperTranslator()->_("E-Class"),
	"clk" => $objCore->getHelperTranslator()->_("CLK"),
	"slk" => $objCore->getHelperTranslator()->_("SLK"),
	"offroad" => $objCore->getHelperTranslator()->_("Offroad"),
	"others-mercedes" => $objCore->getHelperTranslator()->_("Others"),
);
$arrModelsSmart = array(
	"all" => $objCore->getHelperTranslator()->_("All"),
	"f2" => $objCore->getHelperTranslator()->_("Fortwo"),
	"f4" => $objCore->getHelperTranslator()->_("Forfour"),
	"roadster" => $objCore->getHelperTranslator()->_("Roadster"),
	"others-smart" => $objCore->getHelperTranslator()->_("Others"),
);
// - prices
$arrPrices['all'] = $objCore->getHelperTranslator()->_("All");
foreach ($objCore->arrPrices as $strPrice) {
	if ($strPrice > 1000) {
		$strPrice = $strPrice - ($strPrice % 1000) + 1000;
	}
	$arrPrices[$strPrice] = number_format($strPrice, 0, "", ".") . ' EUR';
}
// - sorting
$arrSorting = array(
	'price' => $objCore->getHelperTranslator()->_("Price"),
	'km' => $objCore->getHelperTranslator()->_("Kilometer"),
)

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $strStyleClass ?>">
	<form>
		<input type="hidden" name="send" value="1">
		<div class="box">
			<label>
				<?= $objCore->getHelperTranslator()->_("Brand") ?>
			</label>
			<select name="brand">
				<? foreach ($arrBrands as $strValue => $strLabel) : ?>
					<? ($objCore->strParameterBrand == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
					<option value="<?= $strValue ?>" <?= $strSelected ?>>
						<?= $strLabel ?>
					</option>
				<? endforeach; ?>
			</select>
		</div>
		
		<? if ($objCore->strParameterBrand == 'mercedes-benz'): ?>
		<div class="box">
			<label>
				<?= $objCore->getHelperTranslator()->_("Model") ?>
			</label>
			<select name="model">
				<? foreach ($arrModelsMercedes as $strValue => $strLabel) : ?>
					<? ($objCore->strParameterModel == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
					<option value="<?= $strValue ?>" <?= $strSelected ?>>
						<?= $strLabel ?>
					</option>
				<? endforeach; ?>
			</select>
		</div>
		<? endif; ?>
		
		<? if ($objCore->strParameterBrand == 'smart'): ?>
		<div class="box">
			<label>
				<?= $objCore->getHelperTranslator()->_("Model") ?>
			</label>
			<select name="model">
				<? foreach ($arrModelsSmart as $strValue => $strLabel) : ?>
					<? ($objCore->strParameterModel == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
					<option value="<?= $strValue ?>" <?= $strSelected ?>>
						<?= $strLabel ?>
					</option>
				<? endforeach; ?>
			</select>
		</div>
		<? endif; ?>		
		
		<div class="box">
			<label>
				<?= $objCore->getHelperTranslator()->_("Price (max.)") ?>
			</label>
			<select name="price">
				<? foreach ($arrPrices as $strValue => $strLabel) : ?>
					<? ($objCore->strParameterPrice == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
					<option value="<?= $strValue ?>" <?= $strSelected ?>>
						<?= $strLabel ?>
					</option>
				<? endforeach; ?>
			</select>
		</div>
		<div class="box">
			<label>
				<?= $objCore->getHelperTranslator()->_("Sorting") ?>
			</label>
			<select name="sorting">
				<? foreach ($arrSorting as $strValue => $strLabel) : ?>
					<? ($objCore->strParameterSorting == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
					<option value="<?= $strValue ?>" <?= $strSelected ?>>
						<?= $strLabel ?>
					</option>
				<? endforeach; ?>
			</select>
		</div>
		<div class="clearer">
			&nbsp;
		</div>
		<div class="buttons">
			<? if ($objCore->bResetLink) : ?>
				<input type="hidden" name="reset">
				<input class="button" type="reset" value="<?= $objCore->getHelperTranslator()->_("Reset") ?>" 
					   title="<?= $objCore->getHelperTranslator()->_("Reset all filter values") ?>">
			<? endif; ?>
		</div>

		<? if ($objCore->nCount < 1) : ?>
			<div class="infos">
				<?= $objCore->getHelperTranslator()->_("No matches found.") ?>
				<?= $objCore->getHelperTranslator()->_("Try a new search.") ?>
				<br>
				<br>
				<?= sprintf($objCore->getHelperTranslator()->_("Or get in %s contact %s with us and we will find a car for you."), '<a href="contact">', '</a>') ?>
			</div>
		<? endif; ?>		
	</form>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>