<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact"));

/*
  <?=file_get_contents($objCore->getBaseUrl() . '/contact/element/form'); ?>
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<h1>
		<?= $objCore->getHelperTranslator()->_("Contact") ?>
	</h1>
	<?=  $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
	<img src="apps/image/512/90/data/images/contact/vogtsburg.jpg">
	<h2>
		Schmolck GmbH &amp; Co. KG
	</h2>
	<p>
		Autorisierter Mercedes-Benz Service und Vermittler <br>
		für Mercedes-Benz PKW und Transporter 
	</p>
	<p>
		Bacchusstraße 19 <br>
		79235 Vogtsburg-Bischoffingen 
	</p>
	<p>
		Tel +49 7641 / 4602-0 <br>
		Fax +49 7641 / 4602-80 <br>
	</p>
	<p>
		<?= $objCore->getHelperTranslator()->_("Mail") ?>
		<a href="<?= $objCore->getHelperLink()->get('mailto:info.bischoffingen@schmolck.de')?>">
			<span class="screen">
				Info Bischoffingen
			</span>
			<span class="print">
				info.drexler@schmolck.de
			</span>
		</a>
	</p>
	<div class="clearer">

	</div>
	<div class="screen">
		<p>
			<?= $objCore->getHelperApi()->getElement('email', 'contact/api/form') ?>				
		</p>
	</div>
</div>