<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Cars"));
$strBaseUrl = $objCore->getHelperApplication()->getBaseUrl();
$nCounter = 0;

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<? if ($objCore->nCars > 0) : ?>
		<div class="loadingmessage">
			<?= $objCore->getHelperTranslator()->_("Loading...") ?>
		</div>	
		<div class="amount">
			<?= sprintf($objCore->getHelperTranslator()->_("%s Hits"), $objCore->nCars) ?>
		</div>
		<div class="list">
			<? foreach ($objCore->arrCars as $arrCar) : ?>		
				<? ($nCounter % 2 == 1) ? $strOdd = 'odd' : $strOdd = ''; ?> 
				<a name="<?= $arrCar['id'] ?>"></a>
				<div class="item <?= $strOdd ?>" data-name="<?= $arrCar['id'] ?>" data-link="<?= $strBaseUrl ?>/mobile/database/detail/id/<?= $arrCar['id'] ?>">
					<div class="title">
						<?= $arrCar['name'] ?>
					</div>
					<div class="data">
						<div class="image">
							<img src="apps/image/200/90/<?= $arrCar['images'][0] ?>">
						</div>
						<div class="infos1">
							<?= $arrCar['fahrzeug'] ?> <br>
							<?= $arrCar['kategorie'] ?> <br>							
							<?= $arrCar['id'] ?> <br>					
						</div>
						<div class="infos2">
							EZ <?= $arrCar['ez'] ?> <br>
							<?= $arrCar['km'] ?> km <br>
						</div>
						<div class="infos3">
							<?= $arrCar['kraftstoff'] ?> <br>
							<?= $arrCar['kw'] ?> kW (<?= $arrCar['ps'] ?> PS) <br>
							<?= $arrCar['getriebe'] ?> <br>
						</div>
						<div class="price">
							<?= $arrCar['preis'] ?> EUR <br>
							<div class="pricenote">
								<?
								if ($arrCar['mwst'] == '1') {
									 echo $objCore->getHelperTranslator()->_("VAT not deductable");
								} else {
									 echo $objCore->getHelperTranslator()->_("VAT deductable");
								}
								?>								
							</div>							
						</div>
						<div class="clearer">
							&nbsp;
						</div>
					</div>
				</div>
				<? $nCounter++ ?>
			<? endforeach; ?>
		</div>
		<? if (count($objCore->arrCars) >= 5) : ?>
			<div class="amount">
				<?= sprintf($objCore->getHelperTranslator()->_("%s Hits"), $objCore->nCars) ?>
			</div>
		<? endif; ?>	
	<? endif; ?>	
	<div class="clearer">
		&nbsp;
	</div>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>