<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">

    <?php foreach ($objCore->arrCars as $arrCar) : ?>		
        <?php // $strCarName = $arrCar['name'] . ' <sup>(' . $arrCar['id'] . ')</sup>' ?>
        <?php $strCarName = $arrCar['name'] ?>
        <?php $objCore->strPageTitle = $strCarName ?>
        <div class="item" data-link="<?= $objCore->strParameterUrl ?>/id/<?= $arrCar['id'] ?>">
            <div class="title">
                <? $objCore->getHelperHtml()->setPageTitle($strCarName); ?>
                <? $strMailInfo = $_SERVER['HTTP_HOST'] . ' - ' . sprintf($objCore->getHelperTranslator()->_("Request for the vehicle %s"), $arrCar['id']); ?>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="image">
                        <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_image", "mobile/element/carousel/id/{$arrCar['id']}"); ?>
                    </div>


                </div>
                <div class="col-md-6 details">

                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th><?= $arrCar['fahrzeug'] ?></th>
                                <th><?= $arrCar['kategorie'] ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>EZ <?= $arrCar['ez'] ?></td>
                                <td><?= $arrCar['km'] ?> km </td>
                            </tr>
                            <tr>
                                <td>
                                    <?= $arrCar['kw'] ?> kW (<?= $arrCar['ps'] ?> PS)
                                </td>
                                <td>
                                    <?= $arrCar['kraftstoff'] ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <?= $arrCar['getriebe'] ?> 
                                </td>
                                <td>
                                    <?= $arrCar['color'] ?> 
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="qrcode">
                                        <img src="<?= $objCore->strQRImage ?>">
                                    </div>
                                </td>
                                <td class="price">
                                    <?= $arrCar['preis'] ?> EUR <br>
                                    <div class="pricenote">
                                        <?
                                        if ($arrCar['mwst'] == '1') {
                                        echo $objCore->getHelperTranslator()->_("VAT not deductable");
                                        } else {
                                        echo $objCore->getHelperTranslator()->_("VAT deductable");
                                        }
                                        ?>		
                                    </div>		
                                </td>

                            </tr>

                        </tbody>
                    </table>


                </div>
            </div>
            <div class="rows">    
                <div class="col-md-6 infos">
                    <?= $arrCar['bemerkung'] ?>
                </div>
                <div class="col-md-6 contact">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">
                                <?= $objCore->getHelperTranslator()->_("Contact"); ?>
                            </h3>
                        </div>
                        <div class="panel-body">
                            <table width="100%">
                                <tr>
                                    <td>
                                        <a href="contact/page/emmendingen">
                                            <img src="apps/image/1024/100/images/cars.schmolck.de/contact/pkw-verkauf-emmendingen.jpg" class="img-thumbnail" title="Emmendingen und Vogtsburg">
                                        </a>
                                    </td>
                                    <td class="spacing">
                                        &nbsp;
                                    </td>
                                    <td>
                                        <a href="contact/page/muellheim">
                                            <img src="apps/image/1024/100/images/cars.schmolck.de/contact/pkw-verkauf-muellheim.jpg" class="img-thumbnail" title="Müllheim">                        
                                        </a>
                                    </td>
                                </tr>
                            </table>
                            <p class="request">
                                <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_form", "mobile/element/form/id/{$arrCar['id']}") ?>				
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    <?php endforeach; ?>

    <?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>