<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact") . " - Emmendingen");
$objCore->strPageTitle = $objCore->getHelperTranslator()->_("Our sales consultants for Emmendingen and Vogtsburg");
$arrPersonInfo = array(
    'Sonja Fross' => 'info.emmendingen@schmolck.de',
    'Anastasija Kopp' => 'info.emmendingen@schmolck.de',
    'Carina Kusnezow' => 'info.emmendingen@schmolck.de',
);
$arrPersonSale = array(
    'Sebastian Heiny' => 'sebastian_heiny.jpg',
    'Mike Mack' => 'mike_mack.jpg',
    'Benedikt Pohl' => 'benedikt_pohl.jpg',
    'Jürgen Rinkenauer' => 'juergen_rinkenauer.jpg',
);
$arrPersonSkoda = array(
    'Roland Henecka' => 'roland.henecka@schmolck.de',
    'Stefan Klopfer' => 'stefan.klopfer@schmolck.de',
    'Lidija Schmal' => 'lidija.schmal@schmolck.de',
    'Alexander Fliegauf' => 'alexander.fliegauf@schmolck.de'
);
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
    <div class="contact">
        <div class="row">
            <div class="col-md-6">
                <div>
                    <h2>
                        Unser Mercedes-Benz Verkaufs-Team
                    </h2>               
                    <img src="apps/image/1024/90/images/cars.schmolck.de/contact/pkw-verkauf-emmendingen.jpg">
                    <table class="table names" width="100%">
                        <tbody>
                            <tr>
                                <?php foreach ($arrPersonSale as $name => $file) : ?>	
                                    <td>                                     
                                        <?= $name ?>
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                        </tbody>                    
                    </table>                
                </div>
                </p>
            </div>
            <div class="col-md-6">
                <div>
                    <h2>
                        Unser ŠKODA Verkaufs-Team
                    </h2>        
                    <img src="apps/image/1024/90/images/cars.schmolck.de/contact/pkw-verkauf-emmendingen-skoda.jpg">
                    <table class="table names" width="100%">
                        <tbody>
                            <tr>
                                <?php foreach ($arrPersonSkoda as $name => $email) : ?>	
                                    <td>
                                        <?php /*
                                          <a href="<?= $objCore->getHelperLink()->get("mailto:{$email}?subject={$strMailInfo}") ?>"><?= $name ?></a>
                                         */ ?>
                                        <?= $name ?>
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                        </tbody>                    
                    </table>                
                </div> 
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6">
                <h3>
                    Schmolck GmbH &amp; Co. KG
                </h3>
                <p>
                    Autorisierter Mercedes-Benz Service und Vermittler <br>
                    der Daimler AG f&uuml;r Mercedes-Benz PKW, NFZ und smart <br>
                    Unimog-Service, Umwelttechnik <br>
                    Am Elzdamm 2 <br>
                    79312 Emmendingen	
                </p>
                <p>
                    Tel +49 7641 / 4602-0 <br>
                    Fax +49 7641 / 4602-80 <br>
                </p>
            </div>
            <div class="col-md-6">        
                <h3>
                    Emil Schmolck GmbH
                </h3>
                <p>
                    ŠKODA Partner <br>
                    Bosch-Service & VW-Service <br>
                    Am Elzdamm 2 <br>
                    79312 Emmendingen	
                </p>
                <p>
                    Tel +49 7641 / 4602-500 <br>
                    Fax +49 7641 / 4602-8500
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="form screen">
                    <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_form", 'mobile/element/form') ?>		
                </div>
            </div>
        </div>
    </div>
</div>