<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Cars"));
$strBaseUrl = $objCore->getHelperApplication()->getBaseUrl();
$nCounter = 0;

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<? if ($objCore->nCars > 0) : ?>
		<div class="amount">
			<?= sprintf($objCore->getHelperTranslator()->_("%s Hits"), $objCore->nCars) ?>
		</div>
		<div class="list">
			<? foreach ($objCore->arrCars as $arrCar) : ?>		
				<? ($nCounter % 2 == 1) ? $strOdd = 'odd' : $strOdd = ''; ?> 
				<a name="<?= $arrCar['KNR'] ?>"></a>
				<div class="item <?= $strOdd ?>" data-name="<?= $arrCar['KNR'] ?>" data-link="<?= $strBaseUrl ?>/cars/database/detail/id/<?= $arrCar['KNR'] ?>">
					<div class="title">
						<?= $arrCar['name'] ?>
					</div>
					<div class="data">
						<div class="image">
							<img src="<?= $arrCar['image'] ?>">
						</div>
						<div class="infos1">
							<?= $arrCar['KAT'] ?> <br>
							<?= $arrCar['KNR'] ?> <br>						
						</div>
						<div class="infos2">
							EZ <?= $arrCar['EZ'] ?> <br>
							<?= $arrCar['KM'] ?> km <br>
						</div>
						<div class="infos3">
							<?= $arrCar['KW'] ?> kW (<?= $arrCar['PS'] ?> PS) <br>
							<?= $arrCar['color'] ?> <br>
						</div>
						<div class="price">
							<?= $arrCar['RP'] ?> EUR <br>
						</div>
						<div class="clearer">
							&nbsp;
						</div>
					</div>
				</div>
				<? $nCounter++ ?>
			<? endforeach; ?>
		</div>
		<? if (count($objCore->arrCars) >= 5) : ?>
			<div class="amount">
				<?= sprintf($objCore->getHelperTranslator()->_("%s Hits"), $objCore->nCars) ?>
			</div>
		<? endif; ?>	
	<? endif; ?>	
	<div class="clearer">
		&nbsp;
	</div>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>