<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->getHelperApi()->getStyleClass() ?>">	
	
	<img src="<?= $objCore->arrImages[$objCore->nNumber] ?>" data-next="<?= $objCore->nNumber + 1 ?>">
	
	<div style="display: none;">
		<? foreach ($objCore->arrImages as $strImage) : ?>	
			<img src="<?= $strImage ?>">
		<? endforeach; ?>
	</div>	
	
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>