<?php
/*
 * INIT
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle("Ups, sorry...");

/*
 * PREP
 */
$strSubject = $_SERVER['HTTP_HOST'] . " - " . $Exception->getMessage();
$strBody = $Exception->getMessage() . "%0D%0A%0D%0A" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];

/*
 * LOG
 */
Schmolck_Tool_Debug::error($Exception->getMessage());

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <h2>
        <?= $objCore->getHelperTranslator()->_("...an error occured!"); ?>
    </h2>
    <p>
        <?= $objCore->getHelperTranslator()->_("If this error occurs repeatedly, we would appreciate a short message"); ?>:
        <a href="mailto:<?= EXCEPTION_ADDRESS ?>?subject=<?= $strSubject ?>&body=<?= $strBody ?>">
            <?= EXCEPTION_ADDRESS ?>
        </a>
    </p>
    <p class="alert alert-danger">
        <strong>
            <?= $objCore->getHelperTranslator()->_("Error message"); ?>
        </strong>:
        <?= $Exception->getMessage(); ?>
    </p>

    <? if (APPLICATION_ENVIRONMENT != 'production') : ?>
        <p style="font-style: italic;">
            <?= $Exception->getLine(); ?>: <?= $Exception->getFile(); ?>
        </p>
        <pre class="infos" style="overflow: auto;"><?= $Exception->getTraceAsString() ?></pre>
    <? endif; ?>
</div>