<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
// - filter
$objCars = new Mobile_Helper($objCore);
$strBrand = $objCars->getFilter('brand');
$strModel = $objCars->getFilter('model');
$strTransmission = $objCars->getFilter('transmission');
$strPrice = $objCars->getFilter('price');
// - options
$arrBrands = $objCars->getFilterOptionsBrands();
$arrOptions = $objCars->getFilterOptionsModels($strBrand);

/*
 * PREPARATION
 */
$strMessage .= $objCore->getHelperTranslator()->_("Dear Sirs,") . PHP_EOL . PHP_EOL;
$strMessage .= $objCore->getHelperTranslator()->_("I am interested in a vehicle with the following criteria:") . PHP_EOL . PHP_EOL;
$strMessage .= $objCore->getHelperTranslator()->_("Brand") . ': ' . $arrBrands[$strBrand] . PHP_EOL;
$strMessage .= $objCore->getHelperTranslator()->_("Model") . ': ' . $arrOptions[$strModel] . PHP_EOL;
//$strMessage .= $objCore->getHelperTranslator()->_("Transmission") . ': ' . $strTransmission. PHP_EOL;
$strMessage .= $objCore->getHelperTranslator()->_("Price") . ': ' . number_format(doubleval($strPrice), 0, "", ".") . ' EUR' . PHP_EOL . PHP_EOL;
$strMessage .= $objCore->getHelperTranslator()->_("With best regards") . PHP_EOL . PHP_EOL;

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <div class="jumbotron">
        <h2>
            <?= $objCore->getHelperTranslator()->_("Your dream car is not listed?") ?>
        </h2>
        <p>
            <?= $objCore->getHelperTranslator()->_("It would be a pleasure for us to find your dream car.") ?>          
        </p>
        <p>
            <?= $objCore->getHelperTranslator()->_("Please, contact us!") ?>          
        </p>
    </div>
    <?=
    $objCore->getHelperElement()->getElement("{$objCore->strStyleId}_form", 'mobile/element/form', array(
        'subject' => $objCore->getHelperTranslator()->_("Search request"),
        'message' => $strMessage
    ))
    ?>   
    <?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>