<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
?>
<div class="ninecol">
    <div class="content">
  
<?= $objCore->getHelperApplication()->getBaseUrl() ?>
        
        <h1>CSS Basic Elements</h1>

        <p>The purpose of this HTML is to help determine what default settings are with CSS and to make sure that all possible HTML Elements are included in this HTML so as to not miss any possible Elements when designing a site.</p>

        <hr />

        <h2>Headings</h2>

        <h1>Heading 1</h1>
        <h2>Heading 2</h2>
        <h3>Heading 3</h3>
        <h4>Heading 4</h4>
        <h5>Heading 5</h5>
        <h6>Heading 6</h6>

        <hr />


        <h2>Paragraph</h2>

        <p>Lorem ipsum dolor sit amet, <a href="#" title="test link">test link</a> adipiscing elit. Nullam dignissim convallis est. Quisque aliquam. Donec faucibus. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam libero nisi, imperdiet at, tincidunt nec, gravida vehicula, nisl. Praesent mattis, massa quis luctus fermentum, turpis mi volutpat justo, eu volutpat enim diam eget metus. Maecenas ornare tortor. Donec sed tellus eget sapien fringilla nonummy. Mauris a ante. Suspendisse quam sem, consequat at, commodo vitae, feugiat in, nunc. Morbi imperdiet augue quis tellus.</p>

        <p>Lorem ipsum dolor sit amet, <em>emphasis</em> consectetuer adipiscing elit. Nullam dignissim convallis est. Quisque aliquam. Donec faucibus. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam libero nisi, imperdiet at, tincidunt nec, gravida vehicula, nisl. Praesent mattis, massa quis luctus fermentum, turpis mi volutpat justo, eu volutpat enim diam eget metus. Maecenas ornare tortor. Donec sed tellus eget sapien fringilla nonummy. Mauris a ante. Suspendisse quam sem, consequat at, commodo vitae, feugiat in, nunc. Morbi imperdiet augue quis tellus.</p>

        <hr />

        <h2>List Type</h2>

        <h3>Definition List</h3>
        <dl>
            <dt>Definition List Title</dt>
            <dd>This is a definition list division.</dd>
        </dl>

        <h3>Ordered List</h3>
        <ol>
            <li>
                List Item 1
                <ol>
                    <li>
                        List Item 1.1
                        <ol>
                            <li>List Item 1.1.1</li>
                            <li>List Item 1.1.2</li>
                            <li>List Item 1.1.3</li>
                        </ol>
                    </li>
                    <li>List Item 1.2</li>
                </ol>	
            </li>
            <li>List Item 2</li>
            <li>List Item 3</li>
        </ol>

        <h3>Unordered List</h3>
        <ul>
            <li>
                List Item 1
                <ul>
                    <li>
                        List Item 1.1
                        <ul>
                            <li>List Item 1.1.1</li>
                            <li>List Item 1.1.2</li>
                            <li>List Item 1.1.3</li>
                        </ul>
                    </li>
                    <li>List Item 1.2</li>
                </ul>	
            </li>
            <li>List Item 2</li>
            <li>List Item 3</li>
        </ul>

        <hr />

        <h2>Fieldsets, Legends, and Form Elements</h2>

        <fieldset>
            <legend>Legend</legend>

            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam dignissim convallis est. Quisque aliquam. Donec faucibus. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam libero nisi, imperdiet at, tincidunt nec, gravida vehicula, nisl. Praesent mattis, massa quis luctus fermentum, turpis mi volutpat justo, eu volutpat enim diam eget metus.</p>

            <form>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <input type="file" id="exampleInputFile">
                    <p class="help-block">Example block-level help text here.</p>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Check me out
                    </label>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>

        </fieldset>

        <hr />

        <h2>Tables</h2>

        <table cellspacing="0" cellpadding="0">
            <tr>
                <th>
                    Table Header 1
                </th>
                <th>
                    Table Header 2
                </th>
                <th>
                    Table Header 3
                </th>
            </tr>
            <tr>
                <td>Division 1</td><td>Division 2</td><td>Division 3</td>
            </tr>
            <tr class="even">
                <td>Division 1</td><td>Division 2</td><td>Division 3</td>
            </tr>
            <tr>
                <td>Division 1</td><td>Division 2</td><td>Division 3</td>
            </tr>

        </table>

        <hr />

        <h2>Misc Stuff - abbr, acronym, pre, code, sub, sup, etc.</h2>

        <p>Lorem <sup>superscript</sup> dolor <sub>subscript</sub> amet, consectetuer adipiscing elit. Nullam dignissim convallis est. Quisque aliquam. <cite>cite</cite>. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam libero nisi, imperdiet at, tincidunt nec, gravida vehicula, nisl. Praesent mattis, massa quis luctus fermentum, turpis mi volutpat justo, eu volutpat enim diam eget metus. Maecenas ornare tortor. Donec sed tellus eget sapien fringilla nonummy. <acronym title="National Basketball Association">NBA</acronym> Mauris a ante. Suspendisse quam sem, consequat at, commodo vitae, feugiat in, nunc. Morbi imperdiet augue quis tellus.  <abbr title="Avenue">AVE</abbr></p>

        <pre><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam dignissim convallis est. Quisque aliquam. Donec faucibus. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam libero nisi, imperdiet at, tincidunt nec, gravida vehicula, nisl. Praesent mattis, massa quis luctus fermentum, turpis mi volutpat justo, eu volutpat enim diam eget metus. Maecenas ornare tortor. Donec sed tellus eget sapien fringilla nonummy. <acronym title="National Basketball Association">NBA</acronym> Mauris a ante. Suspendisse quam sem, consequat at, commodo vitae, feugiat in, nunc. Morbi imperdiet augue quis tellus.  <abbr title="Avenue">AVE</abbr></p></pre>

    </div>
</div>
<div class="threecol last sidebar">
    <div class="sidebar">
        <p>
            Lorem ipsum dolor sit <a href="#">amet</a>, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet <a href="#">amet</a> kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit <a href="#">amet</a>.   
        </p>
    </div>
</div>