<!DOCTYPE html>
<html>
	<head>
		<base href="<?= $objCore->getHelperApplication()->getBaseUrl() ?>/">
		<meta charset="utf-8"/>
		<title>
			<?= $strPageTitle ?> Schmolck cars 
		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Open+Sans'>
		<link rel="stylesheet" type="text/css" href="apps/style/lib/cssgrid/1140.css"/>
		<!--[if lte IE 9]><link rel="stylesheet" href="apps/style/lib/css/cssgrid/ie.css" type="text/css" media="screen" /><![endif]-->
		<link rel="stylesheet/less" type="text/css" href="apps/style/<?= $this->getViewStyleFile() ?>" media="all"/>

		<script type="text/javascript" src="apps/script/<?= $this->getViewScriptFile() ?>"></script>

		<!--
		Memory Peak Usage: <?= Schmolck_Tool_File::convertBytes(memory_get_peak_usage()) ?>
		-->
	</head>
	<body>
		<div id="quicklinks" class="container">
			<div class="row">
				<div class="twelvecol last">
					<ul>
						<li>
							<a href="http://news.schmolck.de" title="<?= $objCore->getHelperTranslator()->_("Switch to 'Schmolck news'") ?>">
								<?= $objCore->getHelperTranslator()->_("news") ?>
							</a>
						</li>
						<li>
							<a href="" title="<?= $objCore->getHelperTranslator()->_("You are already here") ?>">
								<?= $objCore->getHelperTranslator()->_("cars") ?>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>		

		<div id="header" class="container">
			<div class="row">
				<div class="sixcol">
					<div class="padding">
						<a href="">
							<img class="logo" src="data/images/logo.png" />
						</a>
						<div class="description">
							<?= $objCore->getHelperTranslator()->_("cars") ?>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div id="navigation" class="container">
			<div class="row">
				<div class="twelvecol last">
					<div class="hlist">
						<ul>
							<li>
								<a href="cars/database/overview">
									<?= $objCore->getHelperTranslator()->_("Cars") ?>
								</a>
							</li>							

							<li>
								<a href="location">
									<?= $objCore->getHelperTranslator()->_("Location") ?>
								</a>
							</li>

							<li>
								<a href="contact">
									<?= $objCore->getHelperTranslator()->_("Contact") ?>
								</a>
							</li>

							<li>
								<a href="imprint">
									<?= $objCore->getHelperTranslator()->_("Imprint") ?>
								</a>
							</li>
						</ul>
					</div>

				</div>
			</div>
		</div>

		<?php if ($objCore->getHelperMessage()->getMessage() != '') : ?>
			<div id="message" class="container slideDown">
				<div class="row">
					<div class="twelvecol last">
						<div class="text">
							<?= $objCore->getHelperMessage()->popMessage() ?>
						</div>
					</div>				
				</div>			
			</div>
		<?php endif; ?>

		<div id="main" class="container">
			<div class="row">
				<?= $this->renderViewHtml() ?>
			</div>
		</div>

		<div id="footer" class="container">
			<div class="row">
				<div class="ninecol">

				</div>
				<div class="threecol last">
					<div class="logo">
						<div class="padding">
							<a href="">
								<img class="logo" src="data/images/logo.png" />
							</a>						
						</div>
					</div>					
				</div>
			</div>
			<div class="row">
				<div class="ninecol">
					<div class="padding">
						<div class="language">
							<?= $objCore->getHelperApi()->getElement('langswitcher', 'translation/api/switcher') ?>				
						</div>										
					</div>
				</div>
				<div class="threecol last">
					<div class="padding">
						<div class="copyright">
							&copy; <?= date('Y') ?> Schmolck
						</div>					
					</div>
				</div>
			</div>
		</div>

		<? if (PIWIK_TRACKING_ID != '') : ?>
			<!-- Piwik -->
			<script type="text/javascript">
				var _paq = _paq || [];
				_paq.push(["trackPageView"]);
				_paq.push(["enableLinkTracking"]);

				(function() {
					var u=(("https:" == document.location.protocol) ? "https" : "http") + "://piwik.schmolck.de/piwik/";
					_paq.push(["setTrackerUrl", u+"piwik.php"]);
					_paq.push(["setSiteId", "<?= PIWIK_TRACKING_ID ?>"]);
					var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
					g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
				})();
			</script>
			<!-- End Piwik Code -->		
		<? endif; ?>
	</body>
</html>