<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Imprint"));
?>
<div class="twelvecol last">
	<div class="content">
		<h1>
			<?= $objCore->getHelperTranslator()->_("Imprint") ?>
		</h1>
		<p>
			<strong>Schmolck GmbH &amp; Co. KG </strong><br>
			Autorisierter Mercedes-Benz Service und Vermittler<br>
			der Daimler AG für Mercedes-Benz PKW, NFZ und smart<br>
			Unimog-Service, Umwelttechnik<br>
			Am Elzdamm 2<br>
			79312 Emmendingen
		</p>
		<p>
			Tel +49 7641 / 4602-0<br>
			Fax +49 7641 / 4602-80<br>
		</p>
		<p>
			Geschäftsführer: Bernhard Schmolck, Jürgen Henninger<br>
			Kommanditgesellschaft, Sitz Emmendingen, Registergericht Emmendingen, HRA 812<br>
			Persönlich haftende Gesellschafterin: Schmolck GmbH, Sitz Müllheim, Registergericht Freiburg, HRB 281 Mü<br>
			Umsatzsteuer-Identifikationsnummer: DE 141 941 057
		</p>
		<hr>
		<p>
			<strong>Schmolck GmbH &amp; Co. KG </strong><br>
			Autorisierter Mercedes-Benz Service und Vermittler<br>
			für Mercedes-Benz PKW und Transporter<br>
			Bacchusstraße 19<br>
			79235 Vogtsburg-Bischoffingen <a href="http://www.schmolck.de/anfahrt-em"><br>
			</a><br>
			Tel +49 7662 / 91123-0<br>
			Fax +49 7662 / 91123-20<br>
		</p>
		<p style="text-align: justify;">Geschäftsführer: Bernhard Schmolck, Jürgen Henninger<br>
			Kommanditgesellschaft, Sitz Emmendingen, Registergericht Emmendingen, HRA 812<br>
			Persönlich haftende Gesellschafterin: Schmolck GmbH, Sitz Müllheim, Registergericht Freiburg, HRB 281 Mü.</p>
		<p style="text-align: justify;">Umsatzsteuer-Identifikationsnummer: DE 141 941 057</p>
		<hr>
		<p style="text-align: justify;"><strong>Autohaus Schmolck GmbH &amp; Co. KG </strong><br>
			Autorisierter Mercedes-Benz Service und Vermittler<br>
			der Daimler AG für Mercedes-Benz und smart<br>
			Unimog Kundendienststation<br>
			Kinzigstraße 5<br>
			79379 Müllheim <a href="http://www.schmolck.de/anfahrt-mue"><br>
			</a><br>
			Tel +49 7631 / 3672-0<br>
			Fax +49 7631 / 3672-80<br>
		</p>
		<p style="text-align: justify;">Geschäftsführer: Bernhard Schmolck, Jürgen Henninger<br>
			Kommanditgesellschaft, Sitz Müllheim, Registergericht Freiburg, HRA 376 Mü.<br>
			Persönlich haftende Gesellschafterin: Schmolck GmbH, Sitz Müllheim, Registergericht Freiburg, HRB 281 Mü.</p>
		<p style="text-align: justify;">Umsatzsteuer-Identifikationsnummer: DE 141 941 145</p>
		<hr>
		<p style="text-align: justify;"><strong>Emil Schmolck GmbH </strong><br>
			Bosch-Service &amp; VW-Service<br>
			Am Elzdamm 2<br>
			79312 Emmendingen <a href="http://www.schmolck.de/anfahrt-em"><br>
			</a><br>
			Tel +49 7641 / 4602-500<br>
			Fax +49 7641 / 4602-8500<br>
		</p>
		<p>Geschäftsführer: Bernhard Schmolck, Jürgen Henninger</p>
		<p>Registergericht Emmendingen, HR-Nr.: HRB 142<br>
			Umsatzsteuer-Identifikationsnummer: DE 812 987 410</p>
		<hr>
		<h2>Web-Auftritt</h2>
		<p>Programmierung &amp; Design: <a href="http://www.pascalschmolck.de/" target="_blank">Pascal Schmolck</a><br>
		</p>
		<hr>
		<h2>Haftungsausschluss</h2>
		<p><strong>Haftung für Inhalte<br>
			</strong>Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen.</p>
		<p style="text-align: justify;">Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei bekannt werden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p>
		<p style="text-align: justify;"><strong>Haftung für Links<br>
			</strong>Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei bekannt werden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p>
		<h2>Urheberrecht</h2>
		<p style="text-align: justify;">Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Beiträge Dritter sind als solche gekennzeichnet. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.</p>
		<p style="text-align: justify;">Die Betreiber der Seiten sind bemüht, stets die Urheberrechte anderer zu beachten bzw. auf selbst erstellte sowie lizenzfreie Werke zurückzugreifen.</p>
		<h2>Datenschutz</h2>
		<p style="text-align: justify;">Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies soweit möglich stets auf freiwilliger Basis. Die Nutzung der Angebote und Dienste ist, soweit möglich, stets ohne Angabe personenbezogener Daten möglich.</p>
		<p style="text-align: justify;">Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.</p>
		<p style="text-align: justify;">Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.</p>
		<p style="text-align: justify;">Quelle: eRecht24.de - <a href="http://www.e-recht24.de/">Rechtsberatung von Anwalt </a>Sören Siebert</p>

	</div>
</div>