<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("URL Shortener"));
$objCore->strPageTitle = $objCore->getHelperTranslator()->_("URL Shortener");
// - CSS classes for error display
$arrElement = array(
    'url' => array(
        'label' => $objCore->getHelperTranslator()->_("URL") . '*',
        'error' => $objCore->strErrorUrl
    )
);
foreach ($arrElement as $element => $value) {
    if ($value['error'] != '') {
        $arrElement[$element]['class'] = 'has-warning';
        $arrElement[$element]['label'] = $value['error'];
    } else {
        $arrElement[$element]['label'] = $value['label'];
    }
}
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?php if ($objCore->strUrlRedirect == ''): ?>
        <h1>
            <?= $objCore->strPageTitle ?>
        </h1>
    <?php endif; ?>
    <?php if ($objCore->strErrorMessage != ''): ?>
        <div class="alert alert-dismissible alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?= $objCore->strErrorMessage ?>
        </div>
    <?php endif; ?>
    <?php if ($objCore->strUrlRedirect != ''): ?>
        <div class="well">
            <h3>
                <?= $objCore->getHelperTranslator()->_("Redirecting to...") ?>
            </h3>
            <h4 class="wrap">
                <a href="<?= $objCore->strUrlRedirect ?>">
                    <?= $objCore->strUrlRedirect ?>
                </a>
            </h4>
        </div>
    <?php else: ?>
        <form>
            <div class="form-group <?= $arrElement['url']['class'] ?>">
                <label for="url" class="control-label">
                    <?= $arrElement['url']['label'] ?>
                </label>
                <input type="text" name="url" class="form-control" value="<?= $objCore->strUrl ?>">
            </div>

            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="<?= $objCore->getHelperTranslator()->_("Shorten") ?>">
            </div>
        </form>
        <?php if ($objCore->strHash != '' && $objCore->strUrl != ''): ?>
            <div class="well">
                <h4 class="wrap">
                    <a href="<?= $objCore->strHash ?>" target="_blank">
                        <?= $objCore->strHash ?>
                    </a>
                </h4>
                <div class="qrcode">
                    <img src="<?= $objCore->strQRImage ?>">
                </div>
            </div>
        <?php endif; ?>

    <?php endif; ?>
    <?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>