<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Cars"));
$strBaseUrl = $objCore->getHelperApplication()->getBaseUrl();

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <? if ($objCore->nCars > 0) : ?>
        <div class="loadingmessage">
            <?= $objCore->getHelperTranslator()->_("Loading...") ?>
        </div>	
        <!--		<div class="amount">
        <?= sprintf($objCore->getHelperTranslator()->_("%s Hits"), $objCore->nCars) ?>
              </div>-->
        <div class="items">
            <? foreach ($objCore->arrCars as $arrCar) : ?>	

                <a name="<?= $arrCar['id'] ?>"></a>
                <div class="item <?= $strOdd ?>" data-name="<?= $arrCar['id'] ?>" data-link="<?= $strBaseUrl ?>/mobile/page/detail/id/<?= $arrCar['id'] ?>">              
                    <div class="image" title="<?= $arrCar['name'] ?>">
                        <img src="apps/image/200/90/<?= $arrCar['images'][0] ?>" class="img-thumbnail">
                    </div>
                    <div class="id">
                        <?= $arrCar['id'] ?>
                    </div>
                    <? ($arrCar['mwst'] == '1' ? $strStar = '*' : $strStar = '') ?>
                    <div class="price">
                        <?= $strStar ?> <?= $arrCar['preis'] ?> EUR 
                    </div>
                </div>
            <? endforeach; ?>
        </div>
        <div class="clearer">
            &nbsp;
        </div>
        <? if (count($objCore->arrCars) >= 25) : ?>
            <div class="amount">
                <?= sprintf($objCore->getHelperTranslator()->_("%s Hits"), $objCore->nCars) ?>
            </div>
        <? endif; ?>	
        <div>
            * <?= $objCore->getHelperTranslator()->_("VAT not deductable"); ?>
        </div>
    <? else: ?>	
        <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_empty", 'mobile/element/empty') ?>				
    <? endif; ?>		
    <div class="clearer">
        &nbsp;
    </div>
    <?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>