<!DOCTYPE html>
<html>
	<head>
		<base href="<?= $this->getBaseUrl() ?>">
		<meta charset="utf-8"/>
		<title>
			Schmolck cars <?= $strPageTitle ?>
		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="lib/css/cssgrid/1140.css"/>
		<!--[if lte IE 9]><link rel="stylesheet" href="lib/css/cssgrid/ie.css" type="text/css" media="screen" /><![endif]-->
		<link rel="stylesheet/less" type="text/css" href="<?= $this->getCoreLESSFile() ?>" media="screen,handheld,print"/>

		<script type="text/javascript" src="lib/js/less/less-1.3.0.min.js"></script>	
		<script type="text/javascript" src="lib/js/jquery/jquery-1.7.1.min.js"></script> 
		<script type="text/javascript" src="<?= $this->getCoreJSFile() ?>"></script>
	</head>
	<body>
		<div id="quicklinks" class="container">
			<div class="row">
				<div class="twelvecol last">
					<ul>
						<li>
							<a href="http://news.schmolck.de" title="<?= $objCore->getHelperTranslator()->_("Switch to 'Schmolck news'") ?>">
								<?= $objCore->getHelperTranslator()->_("news") ?>
							</a>
						</li>
						<li>
							<a href="" title="<?= $objCore->getHelperTranslator()->_("You are already here") ?>">
								<?= $objCore->getHelperTranslator()->_("cars") ?>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>		

		<div id="header" class="container">
			<div class="row">
				<div class="sixcol">
					<div class="padding">
						<a href="">
							<img class="logo" src="data/images/logo.png" />
						</a>
						<div class="description">
							<?= $objCore->getHelperTranslator()->_("cars") ?>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div id="navigation" class="container">
			<div class="row">
				<div class="twelvecol last">
					<div class="hlist">
						<ul>
							<li>
								<a href="">
									<?= $objCore->getHelperTranslator()->_("Home") ?>
								</a>
							</li>

							<li>
								<a href="content/static/location">
									<?= $objCore->getHelperTranslator()->_("Location") ?>
								</a>
							</li>

							<li>
								<a href="content/static/contact">
									<?= $objCore->getHelperTranslator()->_("Contact") ?>
								</a>
							</li>

							<li>
								<a href="content/static/imprint">
									<?= $objCore->getHelperTranslator()->_("Imprint") ?>
								</a>
							</li>
						</ul>
					</div>

				</div>
			</div>
		</div>

		<div id="main" class="container">
			<div class="row">
				<?= $this->renderViewHtml() ?>
			</div>
		</div>

		<div id="footer" class="container">
			<div class="row">
				<div class="ninecol">

				</div>
				<div class="threecol last">
					<div class="logo">
						<div class="padding">
							<a href="">
								<img class="logo" src="data/images/logo.png" />
							</a>						
						</div>
					</div>					
				</div>
			</div>
			<div class="row">
				<div class="ninecol">
					<div class="padding">
						<div class="language" title="<?= $htmlLangSwitcherTitle ?>">
							<?= $htmlLangSwitcher ?>
						</div>										
					</div>
				</div>
				<div class="threecol last">
					<div class="padding">
						<div class="copyright">
							&copy; <?= date('Y') ?> Schmolck
						</div>					
					</div>
				</div>
			</div>
		</div>
	</body>
</html>