<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
// - style
$strStyleClass = $objCore->getHelperApi()->getStyleClass();
// - button
$strButtonLabel = sprintf($objCore->getHelperTranslator()->_("Display %s hits"), $objCore->nCount);

/*
 * PREPARATION
 */
// - brands
$arrBrands = array(
	'all' => $objCore->getHelperTranslator()->_("All"),
	'mercedes-benz' => $objCore->getHelperTranslator()->_("Mercedes-Benz"),
	'smart' => $objCore->getHelperTranslator()->_("smart"),
	'volkswagen' => $objCore->getHelperTranslator()->_("Volkswagen"),
	'others' => $objCore->getHelperTranslator()->_("Others"),
);
// - types
$arrTypes = array(
	'all' => $objCore->getHelperTranslator()->_("All"),
	'geschaeftswagen' => $objCore->getHelperTranslator()->_("Company Cars"),
	'jahreswagen' => $objCore->getHelperTranslator()->_("Jahreswagen"),
	'gebrauchtwagen' => $objCore->getHelperTranslator()->_("Secondhand Cars"),
);
// - prices
$arrPrices['all'] = $objCore->getHelperTranslator()->_("All");
foreach ($objCore->arrPrices as $strPrice) {
	if ($strPrice > 1000) {
		$strPrice = $strPrice - ($strPrice % 1000) + 1000;
	}
	$arrPrices[$strPrice] = number_format($strPrice, 0, "", ".") . ' EUR';
}

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $strStyleClass ?>">
	<div class="filter">
		<form>
			<input type="hidden" name="send" value="1">
			<p>
				<label>
					<?= $objCore->getHelperTranslator()->_("Brand") ?>
				</label>
				<select name="brand">
					<? foreach ($arrBrands as $strValue => $strLabel) : ?>
						<? ($objCore->strParameterBrand == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
						<option value="<?= $strValue ?>" <?= $strSelected ?>>
							<?= $strLabel ?>
						</option>
					<? endforeach; ?>
				</select>

				<label>
					<?= $objCore->getHelperTranslator()->_("Type") ?>
				</label>
				<select name="type">
					<? foreach ($arrTypes as $strValue => $strLabel) : ?>
						<? ($objCore->strParameterType == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
						<option value="<?= $strValue ?>" <?= $strSelected ?>>
							<?= $strLabel ?>
						</option>
					<? endforeach; ?>
				</select>

				<label>
					<?= $objCore->getHelperTranslator()->_("Price") ?>
				</label>
				<select name="price">
					<? foreach ($arrPrices as $strValue => $strLabel) : ?>
						<? ($objCore->strParameterPrice == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
						<option value="<?= $strValue ?>" <?= $strSelected ?>>
							<?= $strLabel ?>
						</option>
					<? endforeach; ?>
				</select>
			</p>
			
			<? if ($objCore->strParameterSend and !$objCore->strParameterReset) : ?>
				<input type="hidden" name="reset">
				<input class="button" type="reset" value="<?= $objCore->getHelperTranslator()->_("Reset") ?>">
			<? endif; ?>
				
			<? if ($objCore->strParameterSend and $objCore->nCount > 0 and !$objCore->strParameterReset) : ?>
				<input class="button highlight" type="button" value="<?= $strButtonLabel ?>">
			<? endif; ?>

			<? if ($objCore->nCount < 1) : ?>
				<div class="infos">
					<?= $objCore->getHelperTranslator()->_("No matches found. Try a new search.") ?>
				</div>
			<? endif; ?>				
		</form>
	</div>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>