<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
// - style
$strStyleClass = $objCore->getHelperApi()->getStyleClass();
// - button
$strButtonLabel = sprintf($objCore->getHelperTranslator()->_("Display %s hits"), $objCore->nCount);

/*
 * PREPARATION
 */
// - brands
$arrBrands = array(
	'all' => $objCore->getHelperTranslator()->_("All"),
	'mercedes-benz' => $objCore->getHelperTranslator()->_("Mercedes-Benz"),
	'smart' => $objCore->getHelperTranslator()->_("smart"),
	'volkswagen' => $objCore->getHelperTranslator()->_("Volkswagen"),
	'others' => $objCore->getHelperTranslator()->_("Others"),
);
$arrTypes = array(
	'all' => $objCore->getHelperTranslator()->_("All"),
	'geschaeftswagen' => $objCore->getHelperTranslator()->_("Company Cars"),
	'jahreswagen' => $objCore->getHelperTranslator()->_("Jahreswagen"),
	'gebrauchtwagen' => $objCore->getHelperTranslator()->_("Secondhand Cars"),
);

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $strStyleClass ?>">
	<div class="filter">
		<form>
			<input type="hidden" name="send" value="1">
			<p>
				<label>
					<?= $objCore->getHelperTranslator()->_("Brand") ?>
				</label>
				<select name="brand">
					<? foreach ($arrBrands as $strValue => $strLabel) : ?>
						<? ($objCore->strParameterBrand == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
						<option value="<?= $strValue ?>" <?= $strSelected ?>>
							<?= $strLabel ?>
						</option>
					<? endforeach; ?>
				</select>
				<label>
					<?= $objCore->getHelperTranslator()->_("Type") ?>
				</label>
				<select name="type">
					<? foreach ($arrTypes as $strValue => $strLabel) : ?>
						<? ($objCore->strParameterType == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
						<option value="<?= $strValue ?>" <?= $strSelected ?>>
							<?= $strLabel ?>
						</option>
					<? endforeach; ?>
				</select>
			</p>
			<? if ($objCore->strParameterSend and $objCore->nCount > 0) : ?>
				<p>
					<input class="button" type="button" value="<?= $strButtonLabel ?>">
				</p>
			<? endif; ?>
			<? if ($objCore->nCount < 1) : ?>
				<div class="infos">
					<?= $objCore->getHelperTranslator()->_("No matches found.") ?>
				</div>
			<? endif; ?>				
		</form>
	</div>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>