<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<h1>
		<?= $objCore->getHelperTranslator()->_("Contact Person") ?>
	</h1>
	<div class="emmendingen">
		<h2>
			Emmendingen	&amp; Vogtsburg
		</h2>
		<div class="box">
			<img src="apps/image/320/100/data/cars/images/contact/sebastianheiny.jpg"><br>
			<a href="<?= $objCore->getHelperLink()->get("mailto:sebastian.heiny@schmolck.de?subject={$strMailInfo}") ?>">
				Sebastian Heiny 
			</a><br>	
			Tel +49 7641 / 4602-116 
		</div>
		<div class="box">
			<img src="apps/image/320/100/data/cars/images/contact/mikemack.jpg"><br>
			<a href="<?= $objCore->getHelperLink()->get("mailto:mike.mack@schmolck.de?subject={$strMailInfo}") ?>">
				Mike Mack 
			</a><br>			
			Tel +49 7641 / 4602-115
		</div>
		<div class="box">
			<img src="apps/image/320/100/data/cars/images/contact/juergenrinkenauer.jpg"><br>
			<a href="<?= $objCore->getHelperLink()->get("mailto:juergen.rinkenauer@schmolck.de?subject={$strMailInfo}") ?>">
				Jürgen Rinkenauer
			</a><br>
			Tel +49 7641 / 4602-113 
		</div>	
		<div class="box">
			<img src="apps/image/320/100/data/cars/images/contact/andreasblakowski.jpg">				<br>
			<a href="<?= $objCore->getHelperLink()->get("mailto:andreas.blakowski@schmolck.de?subject={$strMailInfo}") ?>">
				Andreas Blakowski 
			</a><br>
			<strong>
				Verkaufsleiter
			</strong>
			<br>
			Tel +49 7641 / 4602-0	
		</div>			
	</div>
	<div class="muellheim">
		<h2>
			Müllheim
		</h2>
		<div class="box">
			<img src="apps/image/320/100/data/cars/images/contact/lievenvanderhoofd.jpg"><br>
			<a href="<?= $objCore->getHelperLink()->get("mailto:lieven.vanderhoofd@schmolck.de?subject={$strMailInfo}") ?>">
				Lieven van der Hoofd 
			</a><br>
			Tel +49 7631 / 3672-0 
		</div>
		<div class="box">
			<img src="apps/image/320/100/data/cars/images/contact/michelmisiuk.jpg">	<br>
			<a href="<?= $objCore->getHelperLink()->get("mailto:michel.misiuk@schmolck.de?subject={$strMailInfo}") ?>">
				Michel Misiuk 
			</a><br>
			Tel +49 7631 / 3672-740  <br>
		</div>		
	</div>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>