<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Locations"));
$objCore->strPageTitle = $objCore->getHelperTranslator()->_("Locations");
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>

    <div class="row">
        <div class="col-md-6 infos">
            <img src="apps/image/512/90/images/cars.schmolck.de/location/vogtsburg.jpg" class="img-thumbnail">
            <h2>
                Schmolck GmbH &amp; Co. KG
            </h2>
            <p>
                Autorisierter Mercedes-Benz Service und Vermittler <br>
                für Mercedes-Benz PKW und Transporter
            </p>
            <p>
                Bacchusstraße 19 <br>
                79235 Vogtsburg-Bischoffingen
            </p>
            <p>
                Tel +49 7641 / 4602-0 <br>
                Fax +49 7641 / 4602-80 <br>
            </p>
            <p>
                <?= $objCore->getHelperTranslator()->_("Mail") ?>
                <a href="<?= $objCore->getHelperLink()->get('mailto:info.bischoffingen@schmolck.de') ?>">
                    <span class="screen">
                        Info Bischoffingen
                    </span>
                    <span class="print">
                        info.drexler@schmolck.de
                    </span>
                </a>
            </p>
            <div class="form screen">
                <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_form", 'mobile/element/form') ?>		
            </div>
        </div>
        <div class="col-md-6 maps">
            <iframe width="100%"
                    height="500"
                    src="https://maps.google.de/maps?hl=de&q=Bacchusstraße 19, 79235 Vogtsburg-Bischoffingen+(Schmolck GmbH & Co. KG)&ie=UTF8&t=&z=17&iwloc=B&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" >
            </iframe> 
        </div>
    </div>
</div>

