<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
    <div class="row">
        <div class="col-md-2">
            <?=
            $objCore->getHelperElement()->getElementCaller("{$objCore->strId}_filter", 'mobile/element/filter', array(
                'resultID' => "{$objCore->strId}_gallery",
                'resultURL' => "mobile/element/gallery"
            ));
            ?>				
        </div>
        <div class="col-md-10">
            <?= $objCore->getHelperElement()->getElementCaller("{$objCore->strId}_gallery", 'mobile/element/gallery') ?>							
        </div>
    </div>
    <div class="rows">
        <div class="col-md-12">
            <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_disclaimer", 'mobile/element/disclaimer') ?>				
        </div>
    </div>
</div>