<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$strStyleClass = $objCore->getHelperApi()->getStyleClass();

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $strStyleClass ?>">	
    <img src="<?= $objCore->arrImages[$objCore->nNumber] ?>" data-next="<?= $objCore->nNumber + 1 ?>" class="img-thumbnail">
    <div style="display: none;">
       <? foreach ($objCore->arrImages as $strImage) : ?>	
	  <img src="<?= $strImage ?>" class="img-thumbnail">
       <? endforeach; ?>
    </div>	
    <?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>