<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact") . " - Müllheim");
$objCore->strPageTitle = $objCore->getHelperTranslator()->_("Our sales consultants for Müllheim");
$arrSeller = array(
    'Benedikt Pohl' => 'benedikt.pohl@schmolck.de',
    'Michel Misiuk' => 'michel.misiuk@schmolck.de',
);
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
    <div class="contact">
        <div class="row">
            <div class="col-md-8">
                <img src="apps/image/1024/90/images/cars.schmolck.de/contact/pkw-verkauf-muellheim.jpg" class="img-thumbnail">
                <table class="names" width="100%">
                    <tr>
                        <?php foreach ($arrSeller as $name => $email) : ?>	
                            <td>
                                <a href="<?= $objCore->getHelperLink()->get("mailto:{$email}?subject={$strMailInfo}") ?>"><?= $name ?></a>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                </table>                
            </div>
            <div class="col-sm-4">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            <?= $objCore->getHelperTranslator()->_("Address") ?>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <a href="location/page/muellheim" class="screen">
                            <img src="apps/image/1024/90/images/cars.schmolck.de/location/muellheim.jpg" class="img-thumbnail">
                        </a>
                        <p>
                            <strong>Autohaus Schmolck GmbH & Co. KG</strong> <br>
                            <a href="location/page/muellheim">
                                Kinzigstraße 5 <br>
                                79379 Müllheim <br>
                            </a>	 
                            <br>
                            Tel +49 7631 / 3672-0 <br>
                            Fax +49 7631 / 3672-80 <br>
                        </p>
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-md-8">        
                <div class="form screen">
                    <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_form", 'mobile/element/form') ?>		
                </div>
            </div>
        </div>
    </div>
</div>