<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact") . " - Müllheim");
$objCore->strPageTitle = $objCore->getHelperTranslator()->_("Our sales consultants for Müllheim");

$arrPersonInfo = array(
    'Linda Schneider' => 'info.muellheim@schmolck.de',
    'Isabella Heid' => 'info.muellheim@schmolck.de',
    'Stefanie Müller' => 'info.muellheim@schmolck.de',
);
$arrPersonSale = array(
    'Benedikt Pohl' => 'benedikt.pohl@schmolck.de',
    'Michel Misiuk' => 'michel.misiuk@schmolck.de',
);
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
    <div class="contact">
        <div class="row">
            <div class="col-md-6">
                <div>
                    <h2>
                        Information &amp; Terminvereinbarung
                    </h2>        
                    <img src="apps/image/1024/90/images/cars.schmolck.de/contact/pkw-zentrale-muellheim.jpg">
                    <table class="table names" width="100%">
                        <tbody>
                            <tr>
                                <?php foreach ($arrPersonInfo as $name => $email) : ?>	
                                    <td>
                                        <?php /*
                                          <a href="<?= $objCore->getHelperLink()->get("mailto:{$email}?subject={$strMailInfo}") ?>"><?= $name ?></a>
                                         */ ?>
                                        <?= $name ?>
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                        </tbody>                    
                    </table>                

                </div> 
            </div>
            <div class="col-md-6">
                <div>
                    <h2>
                        Verkauf
                    </h2>                     
                    <img src="apps/image/1024/90/images/cars.schmolck.de/contact/pkw-verkauf-muellheim.jpg">
                    <table class="table names" width="100%">
                        <tbody>
                            <tr>
                                <?php foreach ($arrPersonSale as $name => $email) : ?>	
                                    <td>
                                        <?php /*
                                          <a href="<?= $objCore->getHelperLink()->get("mailto:{$email}?subject={$strMailInfo}") ?>"><?= $name ?></a>
                                         */ ?>
                                        <?= $name ?>
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                        </tbody>
                    </table>                 
                </div>
                </p>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6">
                <h3>
                    Autohaus Schmolck GmbH &amp; Co. KG
                </h3>
                <p>
                    Autorisierter Mercedes-Benz Service und Vermittler <br>
                    der Daimler AG für Mercedes-Benz und smart <br>
                    Unimog Kundendienststation<br>
                    Kinzigstraße 5 <br>
                    79379 Müllheim			
                </p>
                <p>
                    Tel +49 7631 / 3672-0 <br>
                    Fax +49 7631 / 3672-80 <br>
                </p>
            </div>
            <div class="col-md-6">        
                <div class="form screen">
                    <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_form", 'mobile/element/form') ?>		
                </div>
            </div>            
        </div>
    </div>
</div>