<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * OUTPUT
 */
?>
<div class="ninecol last">
	<div class="content">
		<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
			<form class="navigation screen">
				<input type="button" class="button" name="back" value="<?= $objCore->getHelperTranslator()->_("Back") ?>">
			</form>					
			
			<div class="detail">
				<? foreach ($objCore->arrCars as $arrCar) : ?>		
					<div class="item" data-link="<?= $objCore->strParameterUrl ?>/id/<?= $arrCar['KNR'] ?>">
						<div class="title">
							<?= $arrCar['name'] ?>
							<? $objCore->getHelperHtml()->setPageTitle($arrCar['name'] . ' (' . $arrCar['KNR'] . ')'); ?>
							<? $strMailInfo = $_SERVER['HTTP_HOST'] . ' - ' . sprintf($objCore->getHelperTranslator()->_("Request for the vehicle %s"), $arrCar['KNR']); ?>
						</div>
						<div class="data">
							<div class="qrcode">
								<img src="<?= $objCore->strQRImage ?>">
							</div>
							<div class="image">
								<?=
								$objCore->getHelperApi()->getElement("{$objCore->strId}_image", 'cars/api/image', array(
									'id' => $arrCar['KNR']
								));
								?>				
							</div>
							<div class="infos1">
								<?= $arrCar['KAT'] ?> <br>
								<?= $arrCar['KNR'] ?> <br>						
							</div>
							<div class="infos2">
								EZ <?= $arrCar['EZ'] ?> <br>
								<?= $arrCar['KM'] ?> km <br>
							</div>
							<div class="infos3">
								<?= $arrCar['KW'] ?> kW (<?= $arrCar['PS'] ?> PS) <br>
								<?= $arrCar['color'] ?> (<?= $objCore->getHelperTranslator()->_("Paint"); ?>) <br>
								<?= $arrCar['polster'] ?> (<?= $objCore->getHelperTranslator()->_("Upholstery"); ?>) <br>
							</div>
							<div class="price">
								<?= $arrCar['RP'] ?> EUR <br>
							</div>
							<div class="clearer">
								&nbsp;
							</div>
							<div class="equipment">
								<div class="row1">
									<? for ($i = 0; $i < count($arrCar["equip"]) / 2; $i++) : ?>
										<?= $arrCar["equip"][$i] ?> <br>
									<? endfor; ?>
								</div>
								<div class="row2">
									<? for ($i = 0; $i < count($arrCar["equip"]) / 2; $i++) : ?>
										<?= $arrCar["equip"][(count($arrCar["equip"]) / 2) + $i] ?> <br>
									<? endfor; ?>
								</div>
							</div>	
							<div class="clearer">
								&nbsp;
							</div>
						</div>
					</div>
				<? endforeach; ?>
			</div>
			
			<form class="navigation screen">
				<input type="button" class="button" name="back" value="<?= $objCore->getHelperTranslator()->_("Back") ?>">
			</form>		
			
			<?= $objCore->getHelperScripts()->renderViewScripts() ?>
		</div>
	</div>
</div>
<div class="threecol last">
	<div class="sidebar">
		<div class="screen">
			<h1>
				<?= $objCore->getHelperTranslator()->_("Contact Person") ?>
			</h1>
			<h2>
				Emmendingen			
			</h2>
			<p>
				<img src="apps/image/350/100/data/images/cars/contact/pkw-verkauf-em.jpg">
			</p>
			<p>
				<a href="<?= $objCore->getHelperLink()->get("mailto:mike.mack@schmolck.de?subject={$strMailInfo}") ?>">
					Mike Mack 
				</a><br>			
				Tel +49 7641 / 4602-115
			</p>
			<p>
				<a href="<?= $objCore->getHelperLink()->get("mailto:andreas.blakowski@schmolck.de?subject={$strMailInfo}") ?>">
					Andreas Blakowski 
				</a><br>
				Tel +49 7641 / 4602-114
			</p>
			
			<p>
				<a href="<?= $objCore->getHelperLink()->get("mailto:sebastian.heiny@schmolck.de?subject={$strMailInfo}") ?>">
					Sebastian Heiny 
				</a><br>	
				Tel +49 7641 / 4602-116 
			</p>

			<h2>
				Müllheim
			</h2>
			<p>
				<img src="apps/image/150/90/data/images/cars/contact/michelmisiuk.jpg">
			</p>
			<p>
				<a href="<?= $objCore->getHelperLink()->get("mailto:michel.misiuk@schmolck.de?subject={$strMailInfo}") ?>">
					Michel Misiuk 
				</a><br>
				Tel +49 7631 / 3672-740  <br>
				Téléphone Français:  <br>
				0682 91 69 85			
			</p>
		</div>

		<div class="print">
			<h3>
				Schmolck GmbH &amp; Co. KG
			</h3>
			<p>
				Am Elzdamm 2 <br>
				79312 Emmendingen
			</p>
			<p>
				<?= $objCore->getHelperTranslator()->_("Tel +49 7641 / 4602-0") ?>
				<br>
				<?= $objCore->getHelperTranslator()->_("Fax +49 7641 / 4602-80") ?>
				<br>
				<a href="#">
					info.emmendingen@schmolck.de
				</a>				
			</p>		
		</div>

	</div>
</div>