<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Overview"));
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
    <div class="contact">
        <div class="row">
            <div class="col-md-6">
                <h1>
                    <?= $objCore->getHelperTranslator()->_("Overview") ?>
                </h1>
            </div>            
        </div>
    </div>
</div>