<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->getHelperApi()->getId() ?>" class="<?= $objCore->getHelperApi()->getStyleClass() ?>">	
	<ul class="bxslider">			
		<li>
			<a href="http://news.schmolck.de" target="_top">
				<img src="images/www.schmolck.de/plugins/image/slider/news.jpg">
			</a>
		</li>
		<li>
			<a href="http://cars.schmolck.de" target="_top">
				<img src="images/www.schmolck.de/plugins/image/slider/verkauf.jpg">
			</a>
		</li>
		<li>
			<a href="http://tuning.schmolck.de" target="_top">
				<img src="images/www.schmolck.de/plugins/image/slider/tuning.jpg">
			</a>
		</li>
		<li>
			<a href="http://autovermietung.schmolck.de" target="_top">
				<img src="images/www.schmolck.de/plugins/image/slider/autovermietung.jpg">
			</a>
		</li>
	</ul>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>