<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
// - style
$strStyleClass = $objCore->getHelperApi()->getStyleClass();
// - button
$strButtonLabel = sprintf($objCore->getHelperTranslator()->_("Display %s hits"), $objCore->nCount);

/*
 * PREPARATION
 */
// - brands
$arrBrands = array(
	'all' => $objCore->getHelperTranslator()->_("All"),
	'mercedes-benz' => $objCore->getHelperTranslator()->_("Mercedes-Benz"),
	'smart' => $objCore->getHelperTranslator()->_("smart"),
	'volkswagen' => $objCore->getHelperTranslator()->_("Volkswagen"),
	'others' => $objCore->getHelperTranslator()->_("Others"),
);
// - types
$arrTypes = array(
	'all' => $objCore->getHelperTranslator()->_("All"),
	'geschaeftswagen' => $objCore->getHelperTranslator()->_("Company Cars"),
	'jahreswagen' => $objCore->getHelperTranslator()->_("Jahreswagen"),
	'gebrauchtwagen' => $objCore->getHelperTranslator()->_("Secondhand Cars"),
);
// - prices
$arrPrices['all'] = $objCore->getHelperTranslator()->_("All");
foreach ($objCore->arrPrices as $strPrice) {
	if ($strPrice > 1000) {
		$strPrice = $strPrice - ($strPrice % 1000) + 1000;
	}
	$arrPrices[$strPrice] = number_format($strPrice, 0, "", ".") . ' EUR';
}
// - kms
$arrKms['all'] = $objCore->getHelperTranslator()->_("All");
foreach ($objCore->arrKms as $strKm) {
	if ($strKm > 1000) {
		$strKm = $strKm - ($strKm % 1000) + 1000;
	}
	$arrKms[$strKm] = number_format($strKm, 0, "", ".") . ' km';
}
// - sorting
$arrSorting = array(
	'price' => $objCore->getHelperTranslator()->_("Price"),
	'km' => $objCore->getHelperTranslator()->_("Kilometer"),
)

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $strStyleClass ?>">
	
	<!--
	<?php
		print_r($_POST);
	?>	
	--!>
	<form>
		<input type="hidden" name="send" value="1">
		<div class="box">
			<label>
				<?= $objCore->getHelperTranslator()->_("Brand") ?>
			</label>
			<select name="brand">
				<? foreach ($arrBrands as $strValue => $strLabel) : ?>
					<? ($objCore->strParameterBrand == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
					<option value="<?= $strValue ?>" <?= $strSelected ?>>
						<?= $strLabel ?>
					</option>
				<? endforeach; ?>
			</select>
		
			<label>
				<?= $objCore->getHelperTranslator()->_("Type") ?>
			</label>
			<select name="type">
				<? foreach ($arrTypes as $strValue => $strLabel) : ?>
					<? ($objCore->strParameterType == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
					<option value="<?= $strValue ?>" <?= $strSelected ?>>
						<?= $strLabel ?>
					</option>
				<? endforeach; ?>
			</select>
		</div>
		<div class="box">
			<label>
				<?= $objCore->getHelperTranslator()->_("Km (max.)") ?>
			</label>
			<select name="km">
				<? foreach ($arrKms as $strValue => $strLabel) : ?>
					<? ($objCore->strParameterKm == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
					<option value="<?= $strValue ?>" <?= $strSelected ?>>
						<?= $strLabel ?>
					</option>
				<? endforeach; ?>
			</select>

			<label>
				<?= $objCore->getHelperTranslator()->_("Price (max.)") ?>
			</label>
			<select name="price">
				<? foreach ($arrPrices as $strValue => $strLabel) : ?>
					<? ($objCore->strParameterPrice == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
					<option value="<?= $strValue ?>" <?= $strSelected ?>>
						<?= $strLabel ?>
					</option>
				<? endforeach; ?>
			</select>
		</div>
		<div class="box">
			<label>
				<?= $objCore->getHelperTranslator()->_("Sorting") ?>
			</label>
			<select name="sorting">
				<? foreach ($arrSorting as $strValue => $strLabel) : ?>
					<? ($objCore->strParameterSorting == $strValue) ? $strSelected = 'selected' : $strSelected = ''; ?>
					<option value="<?= $strValue ?>" <?= $strSelected ?>>
						<?= $strLabel ?>
					</option>
				<? endforeach; ?>
			</select>
		</div>
		<div class="clearer">
			&nbsp;
		</div>
		<div class="buttons">
			<? if ($objCore->bResetLink) : ?>
				<input type="hidden" name="reset">
				<input class="button" type="reset" value="<?= $objCore->getHelperTranslator()->_("Reset") ?>" 
					   title="<?= $objCore->getHelperTranslator()->_("Reset all filter values") ?>">
			<? endif; ?>

			<? if ($objCore->strParameterSend and $objCore->nCount > 0 and !$objCore->strParameterReset) : ?>
				<input class="button highlight" type="button" value="<?= $strButtonLabel ?>">
			<? endif; ?>
		</div>

		<? if ($objCore->nCount < 1) : ?>
			<div class="infos">
				<?= $objCore->getHelperTranslator()->_("No matches found. Try a new search.") ?>
			</div>
		<? endif; ?>		
	</form>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>