<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->getHelperApi()->getStyleId() ?>" class="<?= $objCore->getHelperApi()->getStyleClass() ?>">

   <div class="row">
      <div class="col-md-2">
         <?=
         $objCore->getHelperApi()->getElementCaller("{$objCore->strId}_filter", 'mobile/element/filter', array(
             'resultID' => "{$objCore->strId}_result"
         ));
         ?>				
      </div>
      <div class="col-md-10">
         <?= $objCore->getHelperApi()->getElementCaller("{$objCore->strId}_result", 'mobile/element/result') ?>				
      </div>
   </div>
</div>