<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Overview"));
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <h4>
        Aufträge pro Filiale
    </h4>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Filiale
                </th>
                <th>
                    2016
                </th>
                <th>
                    2015
                </th>
                <th>
                    2014
                </th>
                <th>
                    2013
                </th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($objCore->arrBusiness as $arrColumns) :
                $nCounter++;
                ?>
                <tr>
                    <td>
                        0<?= $nCounter ?>
                    </td>
                    <?php
                    foreach ($arrColumns as $strColumn):
                        ?>
                        <td>
                            <?= number_format($strColumn, 0, ',', '.') ?>
                        </td>
                        <?php
                    endforeach;
                    ?>
                </tr>
                <?php
            endforeach;
            ?>
        </tbody>
    </table>
</div>