<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Cars"));
$strBaseUrl = $objCore->getHelperApplication()->getBaseUrl();
$nCounter = 0;

/*
 * OUTPUT
 */
?>
<div class="ninecol last">
	<div class="content">
		<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
			<div class="list">
				<? foreach ($objCore->arrCars as $arrCar) : ?>		
					<? ($nCounter % 2 == 1) ? $strOdd = 'odd' : $strOdd = ''; ?> 
					<div class="item <?= $strOdd ?>" data-link="<?= $strBaseUrl ?>/cars/database/detail/id/<?= $arrCar['KNR'] ?>">
						<div class="title">
							<?= $arrCar['name'] ?>
						</div>
						<div class="data">
							<div class="image">
								<img src="<?= $arrCar['image'] ?>">
							</div>
							<div class="infos1">
								<?= $arrCar['KAT'] ?> <br>
								<?= $arrCar['KNR'] ?> <br>						
							</div>
							<div class="infos2">
								EZ <?= $arrCar['EZ'] ?> <br>
								<?= $arrCar['KM'] ?> km <br>
							</div>
							<div class="infos3">
								<?= $arrCar['KW'] ?> kW (<?= $arrCar['PS'] ?> PS) <br>
								<?= $arrCar['color'] ?> <br>
							</div>
							<div class="price">
								<?= $arrCar['RP'] ?> EUR <br>
							</div>
							<div class="clearer">
								&nbsp;
							</div>
						</div>
					</div>
					<? $nCounter++ ?>
				<? endforeach; ?>
			</div>
			<?= $objCore->getHelperScripts()->renderViewScripts() ?>
		</div>
	</div>
</div>
<div class="threecol last">
	<div class="sidebar">
		<h3>
			Schmolck GmbH &amp; Co. KG
		</h3>
		<p>
			<a href="content/static/location" title="<?= $objCore->getHelperTranslator()->_("Location") ?>">
				Am Elzdamm 2
				<br>
				79312 Emmendingen
			</a>		
		</p>
		<p>
			<?= $objCore->getHelperTranslator()->_("Tel +49 7641 / 4602-0") ?>
			<br>
			<?= $objCore->getHelperTranslator()->_("Fax +49 7641 / 4602-80") ?>

		</p>
		<div class="screen">
			<div id="email" class="loading">
				<script>
					Schmolck_Framework_Helper_Api({
						id: 'email',
						url: 'api/contact/form'
					});
				</script>
			</div>
		</div>
	</div>
</div>