<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Cars"));

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<div class="ninecol last">
		<div class="content">
			<h1>
				<?= $objCore->getHelperTranslator()->_("Cars") ?>
			</h1>
			<?= $objCore->getHelperApi()->getElement('cars', 'cars/search/index') ?>				
		</div>
	</div>
	<div class="threecol last">
		<div class="sidebar">
			<h1>
				<?= $objCore->getHelperTranslator()->_("Contact") ?>
			</h1>
			<h2>
				Emmendingen
			</h2>
			<p>
				Tel +49 7641 / 4602-0 <br>
				Fax +49 7641 / 4602-80 <br>
			</p>
			<p>
				<?= $objCore->getHelperTranslator()->_("Mail") ?>
				<a href="<?= $objCore->getHelperLink()->get('mailto:info.emmendingen@schmolck.de')?>">
					<span class="screen">
						Info Emmendingen
					</span>
					<span class="print">
						info.emmendingen@schmolck.de
					</span>
				</a>
			</p>
			
			<h2>
				Müllheim
			</h2>
			<p>
				Tel +49 7631 / 3672-0 <br>
				Fax +49 7631 / 3672-80 <br>
			</p>
			<p>
				<?= $objCore->getHelperTranslator()->_("Mail") ?>
				<a href="<?= $objCore->getHelperLink()->get('mailto:info.muellheim@schmolck.de')?>">
					<span class="screen">
						Info Müllheim
					</span>
					<span class="print">
						info.muellheim@schmolck.de
					</span>
				</a>
			</p>
			
			<p>
				<div class="screen">
					<?=
					$objCore->getHelperApi()->getElement('email', 'cars/contact/form', array(
						'id' => ' '
					))
					?>				
				</div>
			</p>
		</div>
	</div>
</div>