<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Cars"));
$strBaseUrl = $objCore->getHelperApplication()->getBaseUrl();
$nCounter = 0;

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<div class="ninecol last">
		<div class="content">
			<div>
				<div id="filter" class="loading">
					<script>
						Schmolck_Framework_Helper_Api({
							id: 'filter',
							url: 'cars/api/filter'
						});
					</script>
				</div>
			</div>
				
			<div>
				<div id="cars" class="loading">
					<script>
						Schmolck_Framework_Helper_Api({
							id: 'cars',
							url: 'cars/api/list'
						});
					</script>
				</div>
			</div>
		</div>
	</div>
	<div class="threecol last">
		<div class="sidebar">
			<h3>
				Schmolck GmbH &amp; Co. KG
			</h3>
			<p>
				<a href="content/static/location" title="<?= $objCore->getHelperTranslator()->_("Location") ?>">
					Am Elzdamm 2
					<br>
					79312 Emmendingen
				</a>		
			</p>
			<p>
				<?= $objCore->getHelperTranslator()->_("Tel +49 7641 / 4602-0") ?>
				<br>
				<?= $objCore->getHelperTranslator()->_("Fax +49 7641 / 4602-80") ?>

			</p>
			<div class="screen">
				<div id="email" class="loading">
					<script>
						Schmolck_Framework_Helper_Api({
							id: 'email',
							url: 'api/contact/form'
						});
					</script>
				</div>
			</div>
		</div>
	</div>
</div>