<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Cars"));

/*
  <?=file_get_contents($objCore->getBaseUrl() . 'contact/element/form'); ?>
 */
?>
<div class="ninecol last">
	<div class="content">
		<h1>
			<?= $objCore->getHelperTranslator()->_("Cars") ?>
		</h1>
		<div id="cars" class="loading">
			<script>
				Schmolck_Framework_Helper_Api({
					id: 'cars',
					url: 'api/cars/overview',
					data: '<?= http_build_query($_GET) ?>&url=' + window.location
				});
			</script>
		</div>
	</div>
</div>
<div class="threecol last">
	<div class="sidebar">

		<h1>
			<?= $objCore->getHelperTranslator()->_("Contact") ?>
		</h1>
		<h3>
			Schmolck GmbH &amp; Co. KG
		</h3>
		<p>
			<a href="content/static/location" title="<?= $objCore->getHelperTranslator()->_("Location") ?>">
				Am Elzdamm 2
				<br>
				79312 Emmendingen
			</a>		
		</p>
		<p>
			<?= $objCore->getHelperTranslator()->_("Tel +49 7641 / 4602-0") ?>
			<br>
			<?= $objCore->getHelperTranslator()->_("Fax +49 7641 / 4602-80") ?>
			<br>
			<?= $objCore->getHelperTranslator()->_("Mail") ?>
			<a href="javascript:Schmolck_Framework_Mail_Link('info.emmendingen', 'schmolck.de');">
				Info Emmendingen
			</a>
		</p>

	</div>
</div>