<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact"));

/*
  <?=file_get_contents($objCore->getBaseUrl() . '/contact/element/form'); ?>
 */
?>
<h1>
	<?= $objCore->getHelperTranslator()->_("Contact") ?>
</h1>
<?=  $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
<h2>
	Autohaus Schmolck GmbH & Co. KG 
</h2>
<p>
	<img src="apps/image/300/90/data/images/contact/muellheim.jpg" style="float: right;">
	Autorisierter Mercedes-Benz Service und Vermittler <br>
	der Daimler AG für Mercedes-Benz und smart <br>
	Unimog Kundendienststation <br>
</p>
<p>
	Kinzigstraße 5 <br>
	79379 Müllheim 
</p>
<p>
	Tel +49 7631 / 3672-0 <br>
	Fax +49 7631 / 3672-80 <br>
</p>
<p>
	<?= $objCore->getHelperTranslator()->_("Mail") ?>
	<a href="<?= $objCore->getHelperLink()->get('mailto:info.muellheim@schmolck.de')?>">
		<span class="screen">
			Info Müllheim
		</span>
		<span class="print">
			info.muellheim@schmolck.de
		</span>
	</a>
</p>
<div class="clearer">
	
</div>
<div class="screen">
	<p>
		<?= $objCore->getHelperApi()->getElement('email', 'contact/api/form') ?>				
	</p>
</div>
