<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact"));

/*
  <?=file_get_contents($objCore->getBaseUrl() . '/contact/element/form'); ?>
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<h1>
		<?= $objCore->getHelperTranslator()->_("Contact") ?>
	</h1>
	<?=  $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
	<div class="contact">
		<div class="muellheim">
			<div class="box">
				<img src="apps/image/320/100/images/cars.schmolck.de/contact/michaelberger.jpg"><br>
				<a href="<?= $objCore->getHelperLink()->get("mailto:michael.berger@schmolck.de?subject={$strMailInfo}") ?>">
					Michael Berger
				</a><br>
				Tel +49 7631 / 3672-0 
			</div>
			<div class="box">
				<img src="apps/image/320/100/images/cars.schmolck.de/contact/michelmisiuk.jpg">	<br>
				<a href="<?= $objCore->getHelperLink()->get("mailto:michel.misiuk@schmolck.de?subject={$strMailInfo}") ?>">
					Michel Misiuk 
				</a><br>
				Tel +49 7631 / 3672-740  <br>
			</div>	
		</div>
	</div>
</div>