<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
?>
<h1>
	<?=$objCore->getHelperTranslator()->_("Ups, sorry...");?>
</h1>
<h2>
	<?=$objCore->getHelperTranslator()->_("...an error occured!");?>
</h2>
<div class="errors">
	<strong>Message:</strong> <?=$Exception->getMessage();?>
</div>
<br>
<div style="font-style: italic;">
<?=$Exception->getLine();?>: <?=$Exception->getFile();?>
</div>
<pre class="infos">
<?=$Exception->getTraceAsString()?>
</pre>