<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);


/*
	<?= $objCore->getHelperApi()->getElement("{$objCore->strId}_image", 'plugins/image/slider', array(
		 'path' => 'images/www.schmolck.de/plugins/image/slider'
	));
	?>
*/		
/*
	<?= $objCore->getHelperApi()->getElement("{$objCore->strId}_image", 'plugins/image/slider', array(
		'path' => 'images/www.schmolck.de/plugins/image/slider',
		'timeout' => 7000,
	));
	?>
 */
		
?>
<div id="<?= $objCore->strId; ?>" class="<?= $objCore->getHelperApi()->getStyleClass() ?>">
	
	<div class="wrapper">
		
		<div class="item">
			<a href="http://news.schmolck.de" target="_top">
				<img src="/images/www.schmolck.de/portal/logo/news.schmolck.de.png">
			</a>
		</div>
		<div class="item">
			<a href="http://cars.schmolck.de" target="_top">
				<img src="/images/www.schmolck.de/portal/logo/cars.schmolck.de.png">
			</a>
		</div>
		<div class="item">
			<a href="http://tuning.schmolck.de" target="_top">
				<img src="/images/www.schmolck.de/portal/logo/tuning.schmolck.de.png">
			</a>
		</div>
		<div class="item">
			<a href="http://autovermietung.schmolck.de" target="_top">
				<img src="/images/www.schmolck.de/portal/logo/autovermietung.schmolck.de.png">
			</a>
		</div>	
		<div class="clear">

		</div>				
	</div>

</div>
