<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * OUTPUT
 */
?>
<form id="<?= $objCore->strId ?>" method="post">
	<input type="hidden" name="send" value="1">
	<p>
		<label>
			<?= $objCore->getHelperTranslator()->_("Name") ?>*
			<span class="error">
				<?= $objCore->arrErrors['name'] ?>
			</span>
		</label>
		<input id="<?= $objCore->strId ?>_name" type="text" name="name" value="<?= $objCore->strName ?>">	
	</p>

	<p>
		<label>
			<?= $objCore->getHelperTranslator()->_("E-Mail") ?>*		
			<span class="error">
				<?= $objCore->arrErrors['email'] ?>
			</span>
		</label>
		<input type="text" name="email" value="<?= $objCore->strEmail ?>">
	</p>

	<p>
		<label>
			<?= $objCore->getHelperTranslator()->_("Your message") ?>*
			<span class="error">
				<?= $objCore->arrErrors['message'] ?>
			</span>
		</label>
		<textarea name="message"><?= $objCore->strMessage ?></textarea>
	</p>

	<p>
		<input class="button" type="submit" value="<?= $objCore->getHelperTranslator()->_("Submit") ?>">
	</p>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</form>