<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Location"));
?>
<div class="twelvecol last">
	<div class="content">
		<h1>
			<?= $objCore->getHelperTranslator()->_("Location") ?>
		</h1>
		<?=  $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
		<div style="float: right; text-align: right;">
			<strong>
				Autohaus Schmolck GmbH & Co. KG 
			</strong>
			<br>
			Kinzigstraße 5 <br>
			79379 Müllheim 
		</div>		
		<p>			
			<div class="screen">
				<form method="get" action="https://maps.google.de/maps" target="_blank">
					<input type="hidden" name="daddr" value="Kinzigstraße 5, 79379 Müllheim">
					<input type="text" name="saddr" title="<?= $objCore->getHelperTranslator()->_("Enter your address here") ?>" style="width: 45%;">
					<input type="submit" value="<?= $objCore->getHelperTranslator()->_("Search") ?>" style="float: none;">
				</form>
			</div>
		</p>
		<p>
			<iframe width="100%" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?ie=UTF8&amp;msa=0&amp;msid=210111196947745233323.00046c60ab25feb767013&amp;t=m&amp;source=embed&amp;ll=47.963261,7.735748&amp;spn=0.441392,0.878906&amp;iwloc=00046c60ce3f7d1376c13&amp;output=embed"></iframe>
			<br>
			<small>
				<a href="https://maps.google.com/maps/ms?ie=UTF8&amp;msa=0&amp;msid=210111196947745233323.00046c60ab25feb767013&amp;t=h&amp;ll=47.963261,7.735748&amp;spn=0.441392,0.878906&amp;z=10&amp;source=embed" target="_blank">
					<?= $objCore->getHelperTranslator()->_("Schmolck Group") ?>
				</a>
				- 
				<?= $objCore->getHelperTranslator()->_("open in a larger map") ?>
			</small>
		</p>
	</div>
</div>