<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Locations"));
$objCore->strPageTitle = $objCore->getHelperTranslator()->_("Locations");
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>

    <div class="row">
        <div class="col-md-6 infos">
            <img src="apps/image/512/90/images/cars.schmolck.de/location/muellheim.jpg" class="img-thumbnail">
            <h4>
                Autohaus Schmolck GmbH &amp; Co. KG
            </h4>
            <p>
                Autorisierter Mercedes-Benz Service und Vermittler <br>
                der Daimler AG für Mercedes-Benz und smart <br>
                Unimog Kundendienststation
            </p>
            <p>
                Kinzigstraße 5 <br>
                79379 Müllheim			
            </p>
            <p>
                Tel +49 7631 / 3672-0 <br>
                Fax +49 7631 / 3672-80 <br>
            </p>
            <p>
                <?= $objCore->getHelperTranslator()->_("Mail") ?>
                <a href="<?= $objCore->getHelperLink()->get('mailto:info.muellheim@schmolck.de') ?>">
                    <span class="screen">
                        Info Müllheim
                    </span>
                    <span class="print">
                        info.muellheim@schmolck.de
                    </span>
                </a>
            </p>
            <div class="form screen">
                <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_form", 'mobile/element/form') ?>		
            </div>
        </div>
        <div class="col-md-6 maps">

            <div class="panel panel-default">
                <div class="panel-body">
                    <iframe width="100%"
                            height="550"
                            src="https://maps.google.de/maps?hl=de&q=Kinzigstraße 5, 79379 Müllheim+(Autohaus Schmolck GmbH & Co. KG)&ie=UTF8&t=&z=17&iwloc=B&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" >
                    </iframe> 
                </div>
            </div>
            
        </div>
    </div>
</div>
