<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Location"));
$objCore->strPageTitle = $objCore->getHelperTranslator()->_("Location");
?>
<div id="<?= $objCore->getHelperApi()->getId() ?>" class="<?= $objCore->getHelperApi()->getStyleClass() ?>">
   <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
   <img src="apps/image/512/90/images/cars.schmolck.de/location/muellheim.jpg" class="img-thumbnail">
   <h2>
      Autohaus Schmolck GmbH &amp; Co. KG
   </h2>
   <p>
      Autorisierter Mercedes-Benz Service und Vermittler <br>
      der Daimler AG für Mercedes-Benz und smart <br>
      Unimog Kundendienststation
   </p>
   <p>
      <a href="https://maps.google.de/maps?q=Kinzigstra%C3%9Fe+5+79379+M%C3%BCllheim&hl=de&ie=UTF8&sll=48.11448,7.856941&sspn=0.039368,0.075874&hnear=Kinzigstra%C3%9Fe+5,+79379+M%C3%BCllheim,+Freiburg,+Baden-W%C3%BCrttemberg&t=m&z=16" target="_blank">
         Kinzigstraße 5 <br>
         79379 Müllheim			
      </a>
   </p>
   <p>
      Tel +49 7631 / 3672-0 <br>
      Fax +49 7631 / 3672-80 <br>
   </p>
   <p>
      <?= $objCore->getHelperTranslator()->_("Mail") ?>
      <a href="<?= $objCore->getHelperLink()->get('mailto:info.muellheim@schmolck.de') ?>">
         <span class="screen">
            Info Müllheim
         </span>
         <span class="print">
            info.muellheim@schmolck.de
         </span>
      </a>
   </p>
</div>

