<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Cars"));
$strBaseUrl = $objCore->getHelperApplication()->getBaseUrl();

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<? if ($objCore->nCars > 0) : ?>
		<div class="amount">
			<?= sprintf($objCore->getHelperTranslator()->_("%s Hits"), $objCore->nCars) ?>
		</div>
		<div class="items">
			<? foreach ($objCore->arrCars as $arrCar) : ?>		
				<a name="<?= $arrCar['KNR'] ?>"></a>
				<div class="item <?= $strOdd ?>" data-name="<?= $arrCar['KNR'] ?>" data-link="<?= $strBaseUrl ?>/cars/database/detail/id/<?= $arrCar['KNR'] ?>">
					<div class="image" title="<?= $arrCar['name'] ?> - <?= $arrCar['RP'] ?> EUR">
						<img src="<?= $arrCar['image'] ?>">
					</div>
				</div>
			<? endforeach; ?>
		</div>
		<div class="clearer">
			&nbsp;
		</div>
		<div class="amount">
			<?= sprintf($objCore->getHelperTranslator()->_("%s Hits"), $objCore->nCars) ?>
		</div>
	<? endif; ?>	
	<div class="clearer">
		&nbsp;
	</div>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>