<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Location"));
?>
<div id="<?= $objCore->getHelperApi()->getId() ?>" class="<?= $objCore->getHelperApi()->getStyleClass() ?>">
	<h1>
		<?= $objCore->getHelperTranslator()->_("Location") ?>
	</h1>
	<?=  $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
	<img src="apps/image/512/90/images/cars.schmolck.de/location/vogtsburg.jpg">
	<h2>
		Schmolck GmbH &amp; Co. KG
	</h2>
	<p>
		Autorisierter Mercedes-Benz Service und Vermittler <br>
		für Mercedes-Benz PKW und Transporter
	</p>
	<p>
		<a href="https://maps.google.de/maps?q=Bacchusstra%C3%9Fe+19+79235+Vogtsburg-Bischoffingen&hl=de&ie=UTF8&sll=48.110855,7.851727&sspn=0.009843,0.018969&hnear=Bacchusstra%C3%9Fe+19,+Bischoffingen+79235+Vogtsburg,+Freiburg,+Baden-W%C3%BCrttemberg&t=m&z=16" target="_blank">
			Bacchusstraße 19 <br>
			79235 Vogtsburg-Bischoffingen
		</a>		
	</p>
	<p>
		Tel +49 7641 / 4602-0 <br>
		Fax +49 7641 / 4602-80 <br>
	</p>
	<p>
		<?= $objCore->getHelperTranslator()->_("Mail") ?>
		<a href="<?= $objCore->getHelperLink()->get('mailto:info.bischoffingen@schmolck.de')?>">
			<span class="screen">
				Info Bischoffingen
			</span>
			<span class="print">
				info.drexler@schmolck.de
			</span>
		</a>
	</p>
</div>

