<!DOCTYPE html>
<html>
	<head>
		<!--
		Memory Peak Usage: <?= Schmolck_Tool_File::convertBytes(memory_get_peak_usage()) ?>
		-->		
		<base href="<?= $objCore->getHelperApplication()->getBaseUrl() ?>">
		<meta charset="utf-8"/>
		<title>
			<?= $strPageTitle ?> Schmolck cars 
		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" type="text/css" href="apps/style/<?= $this->getLayoutStyleFile() ?>" media="all"/>
		<script type="text/javascript" src="apps/script/<?= $this->getLayoutScriptFile() ?>"></script>		
	</head>
	<body>
		<div class="wrapper">
			<div id="header">
					<div class="logo">
						<a href=""><img class="title" src="data/images/logo/schmolck-pkw-verkauf.png" /></a>
					</div>	
					<div class="navigation">
						<ul>
							<li>
								<a href="cars/database/overview">
									<?= $objCore->getHelperTranslator()->_("Cars") ?>
								</a>
							</li>							

							<li>
								<a href="location">
									<?= $objCore->getHelperTranslator()->_("Location") ?>
								</a>
							</li>

							<li>
								<a href="contact">
									<?= $objCore->getHelperTranslator()->_("Contact") ?>
								</a>
							</li>

							<li>
								<a href="imprint">
									<?= $objCore->getHelperTranslator()->_("Imprint") ?>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
			
		
		
		
		
		
		
		
<!--		<div id="header" class="container">
			<div class="row">
				<div class="twelvecol last">
					<div class="logo">
						<a href=""><img class="title" src="data/images/logo/schmolck-pkw-verkauf.png" /></a>
					</div>	
					<div class="navigation">
						<ul>
							<li>
								<a href="cars/database/overview">
									<?= $objCore->getHelperTranslator()->_("Cars") ?>
								</a>
							</li>							

							<li>
								<a href="location">
									<?= $objCore->getHelperTranslator()->_("Location") ?>
								</a>
							</li>

							<li>
								<a href="contact">
									<?= $objCore->getHelperTranslator()->_("Contact") ?>
								</a>
							</li>

							<li>
								<a href="imprint">
									<?= $objCore->getHelperTranslator()->_("Imprint") ?>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>-->

		<?php if ($objCore->getHelperMessage()->getMessage() != '') : ?>
			<div id="message" class="container slideDown">
				<div class="row">
					<div class="twelvecol last">
						<div class="text">
							<?= $objCore->getHelperMessage()->popMessage() ?>
						</div>
					</div>				
				</div>			
			</div>
		<?php endif; ?>

		<div id="main" class="container">
			<div class="row">
				<?= $this->renderViewHtml() ?>
			</div>
		</div>
		
		<div id="contact" class="container print">
			<div class="row">
				<div class="twelvecol last">
					<table>
						<tr>
							<td>
								<h3>
									Schmolck GmbH &amp; Co. KG
								</h3>
								<p>
									Am Elzdamm 2 <br>
									79312 Emmendingen
								</p>
								<p>
									Bacchusstraße 19 <br>
									79235 Vogtsburg-Bischoffingen 
								</p>
								<p>
									Tel +49 7641 / 4602-0 <br>
									Fax +49 7641 / 4602-80 <br>
								</p>
								<p>
									<a href="<?= $objCore->getHelperLink()->get('mailto:info.emmendingen@schmolck.de')?>">
										info.emmendingen@schmolck.de
									</a>
								</p>	
							</td>
							<td style="text-align: right;">
								<h3>
									Autohaus Schmolck GmbH & Co. KG 
								</h3>
								<p>
									Kinzigstraße 5 <br>
									79379 Müllheim 
								</p>
								<p>
									Tel +49 7631 / 3672-0 <br>
									Fax +49 7631 / 3672-80 <br>
								</p>
								<p>
									<a href="<?= $objCore->getHelperLink()->get('mailto:info.muellheim@schmolck.de')?>">
										info.muellheim@schmolck.de
									</a>
								</p>
							</td>
						</tr>
					</table>						
				</div>
			</div>
		</div>
		
		<div id="footer" class="container">
			<div class="row">
				<div class="ninecol">

				</div>
				<div class="threecol last">
					<div class="logo">
						<a href="">
							<img class="logo" src="data/images/logo/footer.png" />
						</a>						
					</div>					
				</div>
			</div>
			<div class="row">
				<div class="ninecol">
					<div class="language">
						<?= $objCore->getHelperApi()->getElement('langswitcher', 'translation/api/switcher') ?>				
					</div>										
				</div>
				<div class="threecol last">
					<div class="copyright">
						&copy; <?= date('Y') ?> Schmolck
					</div>					
				</div>
			</div>
		</div>

		<? if (PIWIK_TRACKING_ID != '') : ?>
			<!-- Piwik -->
			<script type="text/javascript">
				var _paq = _paq || [];
				_paq.push(["trackPageView"]);
				_paq.push(["enableLinkTracking"]);

				(function() {
					var u=(("https:" == document.location.protocol) ? "https" : "http") + "://piwik.schmolck.de/piwik/";
					_paq.push(["setTrackerUrl", u+"piwik.php"]);
					_paq.push(["setSiteId", "<?= PIWIK_TRACKING_ID ?>"]);
					var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
					g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
				})();
			</script>
			<!-- End Piwik Code -->		
		<? endif; ?>
	</body>	
</html>