<div class="disclaimer">
    <p>
        *) Weitere Informationen zum offiziellen Kraftstoffverbrauch und zu den 
        offiziellen spezifischen CO2-Emissionen und gegebenenfalls zum 
        Stromverbrauch neuer Pkw können dem 'Leitfaden über den offiziellen 
        Kraftstoffverbrauch, die offiziellen spezifischen CO2-Emissionen und 
        den offiziellen Stromverbrauch neuer Pkw' entnommen werden, der an 
        allen Verkaufsstellen und bei der 'Deutschen Automobil Treuhand GmbH' 
        unentgeltlich erhältlich ist unter 
        <a href="www.dat.de" target="_blank">www.dat.de</a>.
    </p>
    <p>
        **) Die CO2-Effizienz wurde auf Grundlage der gemessenen CO2-Emmissionen unter Berücksichtigung der Masse des Fahrzeugs emittelt.
    </p>
</div>
