<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$strVersionPath = $objCore->getHelperApplication()->getActionPath();
$strVersionFile = 'version.txt';
$strVersion = strip_tags(file_get_contents($strVersionPath . '/' . $strVersionFile));
?>
<h1>
   JSON API
</h1>
<h2>
   Version
</h2>
<?=$strVersion?>
<h2>
   Parameter
</h2>
<h3>
   functions
</h3>
<ul>
   <li>
      <a href="mobile/api/json/function/getFilterOptions">
         getFilterOptions
      </a>
      </li>
</ul>
