<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$strVersionPath = $objCore->getHelperApplication()->getActionPath();
?>
<h1>
    JSON API 2.0.0
</h1>
<h2>
    Functions
</h2>
<h3>
    Filter
</h3>
<ul>
    <li>
        <a href="mobile/api/json/function/getFilterOptions">
            getFilterOptions
        </a>
    </li>
</ul>
<h3>
    Result
</h3>
<ul>
    <li>
        <a href="mobile/api/json/function/getCarsFiltered">
            getCarsFiltered
        </a>
    </li>
</ul>
