<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
    <div class="detail">

        <? foreach ($objCore->arrCars as $arrCar) : ?>		
            <h1>
                <?= $arrCar['name'] ?>
            </h1>
            <div class="item" data-link="<?= $objCore->strParameterUrl ?>/id/<?= $arrCar['id'] ?>">
                <div class="title">
                    <? $objCore->getHelperHtml()->setPageTitle($arrCar['name'] . ' (' . $arrCar['id'] . ')'); ?>
                    <? $strMailInfo = $_SERVER['HTTP_HOST'] . ' - ' . sprintf($objCore->getHelperTranslator()->_("Request for the vehicle %s"), $arrCar['id']); ?>
                </div>
                <div class="data">
                    <div class="qrcode1">
                        <img src="<?= $objCore->strQRImage ?>">
                    </div>
                    <div class="image">
                        <?=
                        $objCore->getHelperApi()->getElement(
                                "{$objCore->strId}_image", 'mobile/api/image', array(
                            'id' => $arrCar['id']
                                )
                        );
                        ?>
                    </div>
                    <div class="infos1">
                        <?= $arrCar['fahrzeug'] ?> <br>
                        <?= $arrCar['kategorie'] ?> <br>
                        <?= $arrCar['id'] ?> <br>						
                    </div>
                    <div class="infos2">
                        EZ <?= $arrCar['ez'] ?> <br>
                        <?= $arrCar['km'] ?> km <br>
                    </div>
                    <div class="infos3">
                        <?= $arrCar['kraftstoff'] ?> <br>
                        <?= $arrCar['kw'] ?> kW (<?= $arrCar['ps'] ?> PS)<br>
                        <?= $arrCar['getriebe'] ?> <br>
    <!--						<?= $arrCar['color'] ?> (<?= $objCore->getHelperTranslator()->_("Paint"); ?>) <br>
                        <?= $arrCar['polster'] ?> (<?= $objCore->getHelperTranslator()->_("Upholstery"); ?>) <br>-->
                    </div>
                    <div class="price">
                        <?= $arrCar['preis'] ?> EUR <br>
                        <div class="pricenote">
                            <?
                            if ($arrCar['mwst'] == '1') {
                                echo $objCore->getHelperTranslator()->_("VAT not deductable");
                            } else {
                                echo $objCore->getHelperTranslator()->_("VAT deductable");
                            }
                            ?>		
                        </div>		
                    </div>
                    <div class="qrcode2">
                        <img src="<?= $objCore->strQRImage ?>">
                    </div>
                    <div class="clearer">
                        &nbsp;
                    </div>
                    <div class="equipment">
                        <?= $arrCar['bemerkung'] ?>
                    </div>	
                    <div class="clearer">
                        &nbsp;
                    </div>
                </div>
            </div>
        <? endforeach; ?>
    </div>			

    <?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>