<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
// - style
$strStyleClass = $objCore->getHelperApi()->getStyleClass();

/*
 * OUTPUT
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $strStyleClass ?>">
	<?=
	$objCore->getHelperApi()->getElement("{$objCore->strId}_filter", 'cars/search/filter', array(
		'resultID' => "{$objCore->strId}_result"
	));
	?>				

	<?= $objCore->getHelperApi()->getElement("{$objCore->strId}_result", 'cars/search/result') ?>				
</div>