<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);

/*
 * OUTPUT
 */
// - detail view
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<div class="detail">
		<? foreach ($objCore->arrCars as $arrCar) : ?>		
			<div class="item" data-link="<?= $objCore->strParameterUrl ?>/id/<?= $arrCar['KNR'] ?>">
				<div class="title">
					<?= $arrCar['name'] ?>
				</div>
				<div class="data">
					<div class="image">
						<img src="<?= $arrCar['image'] ?>">
					</div>
					<div class="infos1">
						<?= $arrCar['KAT'] ?> <br>
						<?= $arrCar['KNR'] ?> <br>						
					</div>
					<div class="infos2">
						EZ <?= $arrCar['EZ'] ?> <br>
						<?= $arrCar['KM'] ?> km <br>
					</div>
					<div class="infos3">
						<?= $arrCar['KW'] ?> kW (<?= $arrCar['PS'] ?> PS) <br>
						<?= $arrCar['color'] ?> <br>
					</div>
					<div class="price">
						<?= $arrCar['RP'] ?> EUR <br>
					</div>
					<div class="clearer">
						&nbsp;
					</div>
					<div class="equipment">
						<table>
							<? foreach ($arrCar["equip"] as $strEquipment) : ?>
								<tr>
									<td><?= $strEquipment ?></td>
								</tr>
							<? endforeach; ?>
						</table>
					</div>					
				</div>
			</div>
		<? endforeach; ?>
	</div>
	<?= $objCore->getHelperScripts()->renderViewScripts() ?>
</div>