<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact"));

/*
  <?=file_get_contents($objCore->getBaseUrl() . '/contact/element/form'); ?>
 */
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
	<h1>
		<?= $objCore->getHelperTranslator()->_("Contact") ?>
	</h1>
	<?=  $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
	<div class="contact">
		<div class="emmendingen">
			<div class="box">
				<img src="apps/image/320/100/data/mobile/images/contact/sebastianheiny.jpg"><br>
				<a href="<?= $objCore->getHelperLink()->get("mailto:sebastian.heiny@schmolck.de?subject={$strMailInfo}") ?>">
					Sebastian Heiny 
				</a><br>	
				Tel +49 7641 / 4602-116 
			</div>
			<div class="box">
				<img src="apps/image/320/100/data/mobile/images/contact/mikemack.jpg"><br>
				<a href="<?= $objCore->getHelperLink()->get("mailto:mike.mack@schmolck.de?subject={$strMailInfo}") ?>">
					Mike Mack 
				</a><br>			
				Tel +49 7641 / 4602-115
			</div>
			<div class="box">
				<img src="apps/image/320/100/data/mobile/images/contact/juergenrinkenauer.jpg"><br>
				<a href="<?= $objCore->getHelperLink()->get("mailto:juergen.rinkenauer@schmolck.de?subject={$strMailInfo}") ?>">
					Jürgen Rinkenauer
				</a><br>
				Tel +49 7641 / 4602-113 
			</div>	
			<div class="box">
				<img src="apps/image/320/100/data/mobile/images/contact/andreasblakowski.jpg"><br>
				<a href="<?= $objCore->getHelperLink()->get("mailto:andreas.blakowski@schmolck.de?subject={$strMailInfo}") ?>">
					Andreas Blakowski 
				</a><br>
				<strong>
					Verkaufsleiter
				</strong>
				<br>
				Tel +49 7641 / 4602-0	
			</div>			
		</div>
	</div>
</div>