<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
?>
<form method="post">
	<p>
		<label>
			<?= $objCore->getHelperTranslator()->_("Name") ?>*
		</label>
		<input type="text" name="name">
	</p>

	<p>
		<label>
			<?= $objCore->getHelperTranslator()->_("E-Mail") ?>*
		</label>
		<input type="text" name="email">
	</p>

	<p>
		<label>
			<?= $objCore->getHelperTranslator()->_("Your message") ?>*
		</label>
		<textarea></textarea>
	</p>

	<p>
		<input class="button" type="reset" value="<?= $objCore->getHelperTranslator()->_("Reset") ?>"> 
		<input class="button" type="submit" value="<?= $objCore->getHelperTranslator()->_("Submit") ?>">
	</p>
</form>