<?php

/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact Form"));
$$this->strId = $objCore->getHelperApi()->getId();
$this->strUri = $objCore->getHelperApplication()->getRequestUri();

///*
// * PARAMETER
// */
//$strSend = strip_tags($_POST['send']);
//$strName = strip_tags($_POST['name']);
//$strEmail = strip_tags($_POST['email']);
//$strMessage = strip_tags($_POST['message']);
//
///*
// * CHECK
// */
//if (!empty($strSend)) {
//	if (!Schmolck_Tool_Validate::checkEmail($strEmail)) {
//		$strEmailError = $objCore->getHelperTranslator()->_("Please enter a valid e-mail address");
//	}
//}

/*
 * OUTPUT
 */
//------------------------------------------------------------------------------
?>
<form id="<?= $$this->strId ?>" method="post">
	<?php
	print_r($_POST);
	?>
	<input type="hidden" name="send" value="1">
	<p>
		<label>
			<?= $objCore->getHelperTranslator()->_("Name") ?>*
		</label>
		<input type="text" name="name" value="<?= $objCore->strName ?>">
	</p>

	<p>
		<label>
			<?= $objCore->getHelperTranslator()->_("E-Mail") ?>*
		</label>
		<input type="text" name="email" value="<?= $strEmail ?>" title="TEST">
	</p>

	<p>
		<label>
			<?= $objCore->getHelperTranslator()->_("Your message") ?>*
		</label>
		<textarea name="message"><?= $strMessage ?></textarea>
	</p>

	<p>
		<input class="button" type="submit" value="<?= $objCore->getHelperTranslator()->_("Submit") ?>">
	</p>
</form>
<?php
//------------------------------------------------------------------------------
?>
<script>
	$(document).ready(function() {		
		/*
		 * TOOLTIP
		 */
		$('#<?= $$this->strId ?> input').tooltip().off("mouseover mouseout");
		
		/*
		 * ACTION
		 */
		$('#<?= $$this->strId ?> input[type=submit]').click(function() {
			<?= $$this->strId ?>_submit();
			return false;
		});
		
		/*
		 * AJAX
		 */
		<?= $$this->strId ?>_submit = function() {
			var strData = $('#<?= $$this->strId ?>').serialize();
			Schmolck_Framework_Api_Element({
				url: '<?= $this->strUri ?>',
				id: '<?= $$this->strId ?>',
				data: strData
			});
		}
	
	});
</script>