<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact") . " - Emmendingen");
$objCore->strPageTitle = $objCore->getHelperTranslator()->_("Our sales consultants for Emmendingen and Vogtsburg");
$arrPersonInfo = array(
    'Sarah Kirstein' => 'info.bischoffingen@schmolck.de',
);
$arrPersonSale = array(
    'Sebastian Heiny' => 'sebastian_heiny.jpg',
    'Mike Mack' => 'mike_mack.jpg',
    'Benedikt Pohl' => 'benedikt_pohl.jpg',
    'Jürgen Rinkenauer' => 'juergen_rinkenauer.jpg',
);
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
    <div class="contact">
        <div class="row">
            <div class="col-md-12">
                <h2>
                    Unser Junge Sterne Verkaufsberater für Emmendingen und Vogtsburg
                </h2>                     
            </div>
            <div class="col-md-8">                
                <img src="apps/image/1024/98/images/cars.schmolck.de/contact/pkw-verkauf-emmendingen.jpg">
                <table class="table names" width="100%">
                    <tbody>
                        <tr>
                            <?php foreach ($arrPersonSale as $name => $email) : ?>	
                                <td>
                                    <?php /*
                                      <a href="<?= $objCore->getHelperLink()->get("mailto:{$email}?subject={$strMailInfo}") ?>"><?= $name ?></a>
                                     */ ?>
                                    <?= $name ?>
                                </td>
                            <?php endforeach; ?>
                        </tr>
                    </tbody>                    
                </table>     
                <h3>
                    Schmolck GmbH & Co. KG
                </h3>
                <p>
                    Autorisierter Mercedes-Benz Service und Vermittler <br>
                    für Mercedes-Benz PKW und Transporter <br>
                    Bacchusstraße 19 <br>
                    79235 Vogtsburg-Bischoffingen <br>
                    <br>
                    Tel +49 7641 / 4602-0 <br>
                    Fax +49 7641 / 4602-80 <br>
                </p>
                <div class="form screen">
                    <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_form", 'mobile/element/form') ?>		
                </div>
            </div>
        </div>
    </div>
</div>