<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact") . " - Emmendingen");
$objCore->strPageTitle = $objCore->getHelperTranslator()->_("Our sales consultants for Emmendingen and Vogtsburg");
$arrSeller = array(
    'Mike Mack' => 'mike.mack@schmolck.de',
    'Sebastian Heiny' => 'sebastian.heiny@schmolck.de',
    'Jürgen Rinkenauer' => 'juergen.rinkenauer@schmolck.de',
    'Andreas Blakowski' => 'andreas.blakowski@schmolck.de'
);
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
    <div class="contact">
        <div class="row">
            <div class="col-md-8">
                <img src="apps/image/1024/90/images/cars.schmolck.de/contact/pkw-verkauf-emmendingen.jpg" class="img-thumbnail">
                <table class="names" width="100%">
                    <tr>
                        <?php foreach ($arrSeller as $name => $email) : ?>	
                            <td>
                                <a href="<?= $objCore->getHelperLink()->get("mailto:{$email}?subject={$strMailInfo}") ?>"><?= $name ?></a>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                </table>                
            </div>
            <div class="col-sm-4">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            <?= $objCore->getHelperTranslator()->_("Address") ?>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <a href="location/page/vogtsburg" class="screen">
                            <img src="apps/image/1024/90/images/cars.schmolck.de/location/vogtsburg.jpg" class="img-thumbnail">
                        </a>
                        <p>
                            <strong>Schmolck GmbH & Co. KG</strong> <br>
                            Bacchusstraße 19 <br>
                            79235 Vogtsburg-Bischoffingen<br>
                            <br>
                            Tel +49 7641 / 4602-0 <br>
                            Fax +49 7641 / 4602-80 <br>
                        </p>
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-md-8">        
                <div class="form screen">
                    <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_form", 'mobile/element/form') ?>		
                </div>
            </div>
        </div>
    </div>
</div>