<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact") . " - Emmendingen");
$arrSeller = array(
    'Mike Mack' => 'mike.mack@schmolck.de',
    'Sebastian Heiny' => 'sebastian.heiny@schmolck.de',
    'Jürgen Rinkenauer' => 'juergen.rinkenauer@schmolck.de',
    'Andreas Blakowski' => 'andreas.blakowski@schmolck.de'
);
?>
<div id="<?= $objCore->strId ?>" class="<?= $objCore->strStyleClass ?>">
   <h1>
      <?= $objCore->getHelperTranslator()->_("Contact") ?>
   </h1> 
   <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
   <div class="contact">
      <div class="row">
         <div class="col-md-8">
            <img src="apps/image/1024/100/images/cars.schmolck.de/contact/pkw-verkauf-emmendingen.jpg">
         </div>
         <div class="col-sm-4">
            <div class="list-group">
               <?php foreach ($arrSeller as $name => $email) : ?>	
                  <a href="<?= $objCore->getHelperLink()->get("mailto:{$email}?subject={$strMailInfo}") ?>" class="list-group-item"><?= $name ?></a>
               <?php endforeach; ?>
            </div>
         </div>
      </div>
      <h2>
         Unsere Junge Sterne Verkaufsberater
         für Emmendingen und Vogtsburg
      </h2>
      <h3>
         Telefon 07641 4602-0
      </h3>
   </div>
   <div class="form">
      <?= $objCore->getHelperApi()->getElement("{$objCore->strId}_form", 'mobile/element/form') ?>				
   </div>
</div>