<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Contact"));

/*
<?=file_get_contents($objCore->getBaseUrl() . 'contact/element/form'); ?>
*/
?>
<div class="sixcol">
	<div class="content">
		<h1>
			<?= $objCore->getHelperTranslator()->_("Contact") ?>
		</h1>
		<p>
			<strong>
				Schmolck GmbH &amp; Co. KG
			</strong>
			<br>
			Autorisierter Mercedes-Benz Service und Vermittler
			<br>
			der Daimler AG f&uuml;r Mercedes-Benz PKW, NFZ und smart
			<br>
			Unimog-Service, Umwelttechnik
		</p>
		<p>
			<a href="content/static/location" title="<?= $objCore->getHelperTranslator()->_("Location") ?>">
				Am Elzdamm 2
				<br>
				79312 Emmendingen
			</a>		
		</p>
		<p>
			<?= $objCore->getHelperTranslator()->_("Tel +49 7641 / 4602-0") ?>
			<br>
			<?= $objCore->getHelperTranslator()->_("Fax +49 7641 / 4602-80") ?>
			<br>
			<?= $objCore->getHelperTranslator()->_("Mail") ?>
			<a href="javascript:Schmolck_Framework_Mail_Link('info.emmendingen', 'schmolck.de');">
				Info Emmendingen
			</a>
		</p>
		<p>
			<a href="http://www.schmolck.de" target="_blank">
				http://www.schmolck.de
			</a>
		</p>
		<p>
			<?= $objCore->getHelperTranslator()->_("You can post your questions to our team in the following languages​​") ?>:
			<br>
		<ul>
			<li>Deutsch</li>
			<li>English</li>
			<li>Français</li>
		</ul>
		</p>
	</div>
</div>
<div class="sixcol last">
	<div class="sidebar">
		<div id="email">
			<script>
				Schmolck_Framework_Api_Element({
					id: 'email',
					url: 'api/contact/form'
				});
			</script>
		</div>
	</div>
</div>
