<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
?>
<div class="sixcol">
	<div class="content">
		<h1>
			<?= $objCore->getHelperTranslator()->_("Contact") ?>
		</h1>
		<p>
			<strong>
				Schmolck GmbH &amp; Co. KG
			</strong>
			<br>
			Autorisierter Mercedes-Benz Service und Vermittler
			<br>
			der Daimler AG f&uuml;r Mercedes-Benz PKW, NFZ und smart
			<br>
			Unimog-Service, Umwelttechnik
		</p>
		<p>
			<a href="content/static/location" title="<?= $objCore->getHelperTranslator()->_("Location") ?>">
				Am Elzdamm 2
				<br>
				79312 Emmendingen
			</a>		
		</p>
		<p>
			<?= $objCore->getHelperTranslator()->_("Tel +49 7641 / 4602-0") ?>
			<br>
			<?= $objCore->getHelperTranslator()->_("Fax +49 7641 / 4602-80") ?>
			<br>
			<?= $objCore->getHelperTranslator()->_("Mail") ?>
			<a href="javascript:Schmolck_Framework_Mail_Link('info.emmendingen', 'schmolck.de');">
				Info Emmendingen
			</a>
		</p>
		<p>
			<a href="http://www.schmolck.de" target="_blank">
				http://www.schmolck.de
			</a>
		</p>
		<p>
			<?= $objCore->getHelperTranslator()->_("You can post your questions to our team in the following languages​​") ?>:
			<br>
		<ul>
			<li>Deutsch</li>
			<li>English</li>
			<li>Français</li>
		</ul>
		</p>
	</div>
</div>
<div class="sixcol last">
	<div class="sidebar">
		<div id="email">
			<form method="post">
				<p>
					<label>
						<?= $objCore->getHelperTranslator()->_("Name") ?>*
					</label>
					<input type="text" name="name">
				</p>

				<p>
					<label>
						<?= $objCore->getHelperTranslator()->_("E-Mail") ?>*
					</label>
					<input type="text" name="email">
				</p>

				<p>
					<label>
						<?= $objCore->getHelperTranslator()->_("Your message") ?>*
					</label>
					<textarea></textarea>
				</p>
				
				<p>
					<input class="button" type="reset" value="<?= $objCore->getHelperTranslator()->_("Reset") ?>"> 
					<input class="button" type="submit" value="<?= $objCore->getHelperTranslator()->_("Submit") ?>">
				</p>
			</form>
		</div>
	</div>
</div>
