<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Location"));
?>
<div id="<?= $objCore->getHelperApi()->getId() ?>" class="<?= $objCore->getHelperApi()->getStyleClass() ?>">
	<h1>
		<?= $objCore->getHelperTranslator()->_("Location") ?>
	</h1>
	<?=  $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>
	<img src="apps/image/512/90/images/cars.schmolck.de/location/emmendingen.jpg">
	<h2>
		Schmolck GmbH &amp; Co. KG
	</h2>
	<p>
		Autorisierter Mercedes-Benz Service und Vermittler <br>
		der Daimler AG f&uuml;r Mercedes-Benz PKW, NFZ und smart <br>
		Unimog-Service, Umwelttechnik
	</p>
	<p>
		<a href="https://maps.google.de/maps?q=Am+Elzdamm+2,+Emmendingen&hl=de&ie=UTF8&sll=48.110862,7.851732&sspn=0.009843,0.017295&hnear=Am+Elzdamm+2,+79312+Emmendingen,+Freiburg,+Baden-W%C3%BCrttemberg&t=m&z=16" target="_blank">
			Am Elzdamm 2 <br>
			79312 Emmendingen	
		</a>		
	</p>
	<p>
		Tel +49 7641 / 4602-0 <br>
		Fax +49 7641 / 4602-80 <br>
	</p>
	<p>
		<?= $objCore->getHelperTranslator()->_("Mail") ?>
		<a href="<?= $objCore->getHelperLink()->get('mailto:info.emmendingen@schmolck.de')?>">
			<span class="screen">
				Info Emmendingen
			</span>
			<span class="print">
				info.emmendingen@schmolck.de
			</span>
		</a>
	</p>
</div>

