<?php
/*
 * INITIALISATION
 */
$objCore = Schmolck_Framework_Core::getInstance($this);
$objCore->getHelperHtml()->setPageTitle($objCore->getHelperTranslator()->_("Locations"));
$objCore->strPageTitle = $objCore->getHelperTranslator()->_("Locations");
?>
<div id="<?= $objCore->getHelperElement()->getStyleId() ?>" class="<?= $objCore->getHelperElement()->getStyleClass() ?>">
    <?= $objCore->getHelperMenu()->getHtml('menu', $objCore->menu) ?>

    <div class="row">
        <div class="col-md-6 infos">
            <img src="apps/image/1024/90/images/cars.schmolck.de/location/emmendingen.jpg">
            <h5>
                Schmolck GmbH &amp; Co. KG
            </h5>
            <p>
                Autorisierter Mercedes-Benz Service und Vermittler <br>
                der Daimler AG f&uuml;r Mercedes-Benz PKW, NFZ und smart <br>
                Unimog-Service, Umwelttechnik
            </p>
            <p>
                Am Elzdamm 2 <br>
                79312 Emmendingen	
            </p>
            <p>
                Tel +49 7641 / 4602-0 <br>
                Fax +49 7641 / 4602-80 <br>
            </p>
            <p>
                <?= $objCore->getHelperTranslator()->_("Mail") ?>
                <a href="<?= $objCore->getHelperLink()->get('mailto:info.emmendingen@schmolck.de') ?>">
                    <span class="screen">
                        Info Emmendingen
                    </span>
                    <span class="print">
                        info.emmendingen@schmolck.de
                    </span>
                </a>
            </p>
            <div class="form screen">
                <?= $objCore->getHelperElement()->getElement("{$objCore->strId}_form", 'mobile/element/form') ?>		
            </div>
        </div>
        <div class="col-md-6 maps screen">
            <div class="panel panel-default">
                <div class="panel-body">
                    <iframe width="100%"
                            height="500"
                            src="https://maps.google.de/maps?hl=de&q=Am Elzdamm 2, 79312 Emmendingen+(Schmolck GmbH & Co. KG)&ie=UTF8&t=&z=17&iwloc=B&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" >
                    </iframe> 
                </div>
            </div>

        </div>
    </div>
</div>

